### ISSUE TITLE
Keyboard nav issue when starting after charge slider

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/coulombs-law#100]
For https://github.com/phetsims/QA/issues/243
Keyboard nav seems to behave a bit oddly if you start in after manipulating one of the charge sliders. I'm in firefox, but chrome was being a bit odd too. I don't think its broken, but you might want to take a look for yourself. It takes two key presses to start in firefox, and it starts in an unexpected location.
But it doesn't do this if you were manipulating anything but those sliders. Chrome does something similar, but it starts at the beginning after manipulating the sliders. Same with edge.

**Comment by mbarlow12** [comment]
@KatieWoe I've confirmed the same behavior in Rutherford Scattering as well, so this is an issue for scenery-phet for the NumberControl. Making an issue and linking.

**Comment by jessegreenberg** [comment]
@mbarlow12 I verified that this issue is fixed from the phetsims/scenery-phet#452.

**Comment by jessegreenberg** [comment]
Removing my assignment, I think this is fixed-pending-testing.

**Comment by arouinfar** [comment]
Since @jessegreenberg verified this issue in https://github.com/phetsims/scenery-phet/issues/452#issuecomment-449506128 and @lmulhall-phet checked this off in rc.9, I will go ahead and close. I am also unable to reproduce in rc.9.
