### ISSUE TITLE
Swap main screenshot with screenshot-alt2

### ISSUE THREAD

**Issue by arouinfar** [phetsims/coulombs-law#102]
For https://github.com/phetsims/QA/issues/243

To make Coulomb's Law more visually distinct from from GFL, @kathy-phet suggesting using the screenshot of the Atomic Scale screen (alt2) as the main screenshot.

@KatieWoe can you swap  the names of [coulombs-law-screenshot](https://github.com/phetsims/coulombs-law/blob/master/assets/coulombs-law-screenshot.png) and [coulombs-law-screenshot-alt2](https://github.com/phetsims/coulombs-law/blob/master/assets/coulombs-law-screenshot-alt2.png)?

**Comment by kathy-phet** [comment]
I think it was actually Oliver who suggested it, but I agree. :)

**Comment by arouinfar** [comment]
Thanks for the suggestion @oliver-phet. :)

**Comment by arouinfar** [comment]
Moved to #104, closing.
