### ISSUE TITLE
Force value readout: Consider semi-transparent black background box

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/coulombs-law#103]
It seems like the white text of the force readout on the left hand ball could benefit from having a semi-transparent black background box so when it overlaps the line dropping down to the ball on the right it is a bit more readable with less interference from the line. 

This is minor and can be considered when outfitted with dynamic description.

**Comment by arouinfar** [comment]
I like this suggestion @kathy-phet! We could add a semi-transparent rectangle that matches the background color behind the entire force string (not just the value). 
![image](https://user-images.githubusercontent.com/8419308/50379483-f6671800-0607-11e9-9759-fe9d71c888ad.png)

I think this is a change we should make across all ISLC sims, not just Coulomb's Law. Leaving self-assigned to open an issue in `inverse-square-law-common`.

**Comment by arouinfar** [comment]
I opened the above issue in ISLC repo, so this can be closed.
