### ISSUE TITLE
Update screenshots before 1.0

### ISSUE THREAD

**Issue by arouinfar** [phetsims/coulombs-law#104]
Consolidating #98 and #102 here.

Given the changes in #101 and #87, all three screenshots need to be retaken. Additionally, we decided to use the Atomic Scale screen as the main screenshot, so the screenshot ordering has been shuffled.

@mbarlow12 before publishing 1.0 can you replace the screenshots with these? I am unable to replace images through the web interface, so I cannot commit them myself.

[coulombs-law-screenshot.png](https://user-images.githubusercontent.com/8419308/50379280-fdd7f280-0602-11e9-9248-a02aebd81da3.png)
[coulombs-law-screenshot-alt1.png](https://user-images.githubusercontent.com/8419308/50379278-fdd7f280-0602-11e9-92b9-2b58eff9094b.png)
[coulombs-law-screenshot-alt2.png](https://user-images.githubusercontent.com/8419308/50379279-fdd7f280-0602-11e9-9f45-ddc6fb25bc9a.png)

**Comment by mbarlow12** [comment]
Can do! Thanks, @arouinfar.

**Comment by arouinfar** [comment]
Looks good in master and 1.0 @mbarlow12. Thanks!
