### ISSUE TITLE
Pusher images look incorrect

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/coulombs-law#109]
Noticed in https://github.com/phetsims/inverse-square-law-common/issues/73  but caused by https://github.com/phetsims/gravity-force-lab-basics/issues/120.  The pushers look like they are pushing harder than they did in the 1.0 release of this sim. The commit that changed this was https://github.com/phetsims/coulombs-law/commit/35ad0608840ab146746cb8a67b69bc32a7163d8f, which removed
```js
    // inherited object node accepts the entire force range. (NOTE: necessary to calculate here as Coulomb's Law allows
    // negative forces while Gravity Force Lab does not.)
    var maxForce = forceConstant * Math.pow( chargeObjectModel.valueRange.max, 2 ) / Math.pow( ( chargeObjectModel.radiusProperty.get() * 2 ), 2 );
    maxForce = maxForce * options.pullRangeMultiplier;
    var minForce = -maxForce;

    // function that determines the current puller image to represent
    var pullForceRange = new Range( minForce, maxForce );
```

and used the model to calculate the force range instead. This was a very reasonable change, but this pullForceRange was used to determine the right image.

**Comment by zepumph** [comment]
@jessegreenberg this was a big oops on my part. Clearly I wasn't testing CL quite well enough then. Thanks for the issue! I found that it made the most sense to override min/max helper functions for the CL model to support values that can be negative. That got things working better.

I tested this by loading the requiresjs in a parallel tab to the published version. I was able to get the puller images, and arrow vectors (which require different calculations) working again. Please review, and take a look at the differences between the two versions. As a side note, please let me know if the other minor layout differences deserve an issue.

**Comment by jessegreenberg** [comment]
Looks really great, thanks for the quick fix!
