### ISSUE TITLE
Pusher/Puller Image updates

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/coulombs-law#11]
Using the new puller images and the pusher images borrowed from https://github.com/phetsims/forces-and-motion-basics leads to rendering & scaling difficulties.

It would be useful to find a way to create some kind of external bounds to which the images could shrink or grow to fill either the width or height component. Other options may exist.

There's also some significant disparity in the placement of the pullers and pushers without changing the location of either charge.

<img width="677" alt="screen shot 2017-07-21 at 4 32 31 pm" src="https://user-images.githubusercontent.com/5711147/28484873-3ebbd236-6e32-11e7-866f-44f2f81546e6.png">

<img width="489" alt="screen shot 2017-07-21 at 4 32 01 pm" src="https://user-images.githubusercontent.com/5711147/28484874-3ebdd39c-6e32-11e7-9c60-a58011b51be2.png">

We also may need to hide the rope connecting the pushers to the charges when the force is zero.
<img width="498" alt="screen shot 2017-07-21 at 4 33 29 pm" src="https://user-images.githubusercontent.com/5711147/28484884-5cb13f88-6e32-11e7-9424-935c821c8abc.png">

**Comment by jessegreenberg** [comment]
Just played with master @mbarlow12, the images look really great going from pushing to pulling!

@mbarlow12 I haven't looked into the details, but do you think it would be possible to translate the images (maybe as part of ```PullerPusherNode.setPull``` or in ```ObjectNode.redrawForce``` so the hand is aligned with the ends of the rope?  That might be easier than modifying bounds.

@arouinfar can you please comment on what should happen with the rope when the force is zero?

**Comment by arouinfar** [comment]
@jessegreenberg @mbarlow12 when the force is zero, use the image of the figure that is standing upright with its arms to the side (puller_1.png). 
![puller_1](https://user-images.githubusercontent.com/8419308/28532805-22c31274-7058-11e7-98f6-5f64d363e0a2.png)

**Comment by jessegreenberg** [comment]
@arouinfar does the rope need to change at all in that case? It may not look as strange when the image is positioned correctly.

**Comment by arouinfar** [comment]
@jessegreenberg I'd like to wait and see what it looks like when the images have been translated correctly. Can you reassign me when it's ready for review?

**Comment by arouinfar** [comment]
If the F=0 case still looks a bit off after translating the images, we can try hiding the rope.

**Comment by jessegreenberg** [comment]
Sounds like a good plan @arouinfar, we will keep it in mind once the images are implemented and ready for review.

**Comment by mbarlow12** [comment]
@jessegreenberg The translating issue was actually separate from initially resizing the images themselves with bounds. So it appears that we'll need to handle both in some way.

**Comment by jessegreenberg** [comment]
It looks like the images are the same size now and vertically aligned, is that because they are they being scaled somewhere in inverse-square-law-common?

**Comment by mbarlow12** [comment]
Correct, it's in PullerPusherNode.js at the moment.

**Comment by jessegreenberg** [comment]
@mbarlow12 it looks like forces-and-motion-basics is using a solution to this problem in ```PusherNode.updateAppliedForcePosition```.  I am wondering if we can use a similar solution here?
