### ISSUE TITLE
Zeros displayed for all values in atomic view standard notation

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/coulombs-law#12]
Here's a screenshot:
<img width="964" alt="screen shot 2017-07-31 at 2 04 54 pm" src="https://user-images.githubusercontent.com/5711147/28796047-4be255c4-75f9-11e7-8cb3-fd27cf44da4c.png">
The issue is that the values are VERY small, and I doubt we want to display ~25 zeros on screen either. One solution would be to disable the scientific notation option so that it's always checked in the atomic screen. Let me know if we have other thoughts.

**Comment by arouinfar** [comment]
@mbarlow12 @jessegreenberg I think it would make the most sense to always display the values in scientific notation and eliminate the Scientific Notation checkbox on the Atomic Scale screen.

**Comment by mbarlow12** [comment]
Thanks  @arouinfar—will do.

**Comment by arouinfar** [comment]
Hold on @mbarlow12!

I've been reviewing master, and the magnitude of the forces at the atomic scale shouldn't be so small. For example, the force between an electron and proton in the Hydrogen atom is on the order of 10^-8 N. What units are you using for distance?

**Comment by mbarlow12** [comment]
@arouinfar You're correct on this—looks like there are some bigger bugs in the code. @jessegreenberg are tracking them down. Thanks for the heads up!

**Comment by mbarlow12** [comment]
Thanks for catching that error @arouinfar. @jessegreenberg and I finally pegged down the scaling issue for the atomic screen. Closing.
