### ISSUE TITLE
mockups for atomic scale

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/coulombs-law#13]
@arouinfar would you mind adding some mockups for the atomic scale to the design document?  @mbarlow12 and I were working on some issues today and had some questions about scaling and distances for that screen.

**Comment by arouinfar** [comment]
Will do @jessegreenberg. I'll tackle it first thing tomorrow morning.

**Comment by jessegreenberg** [comment]
Great, thank you!

**Comment by arouinfar** [comment]
@jessegreenberg @mbarlow12 I've updated the Controls and Mockups sections of the design doc. If there's any particular situation you'd like to see mocked up, or have any further questions, please let me know.
