### ISSUE TITLE
Design screen icons

### ISSUE THREAD

**Issue by arouinfar** [phetsims/coulombs-law#14]

**Comment by arouinfar** [comment]
Ideas from today's design meeting:

Macro: Two charges close together
Atomic: One figure leaning back + charge

**Comment by arouinfar** [comment]
I've mocked up two options at different zoom levels based on the suggestions from last week's design meeting. The lower options translate a bit better to the navbar icons, but I don't think it's a huge difference. Can you take a look @ariel-phet?


<img width="593" alt="screen shot 2017-09-06 at 5 04 19 pm" src="https://user-images.githubusercontent.com/8419308/30138423-8674cd22-9325-11e7-8759-c2695c1b4941.png">

**Comment by ariel-phet** [comment]
@arouinfar I think the atomic icon is good, I like the lower one a bit more (no reason I can particularly articulate)

For the macro, I think I would use something like upper one, but maybe make the charges a bit smaller and include some iconic force arrows?

**Comment by arouinfar** [comment]
Thanks for the feedback @ariel-phet! 

>  I think the atomic icon is good, I like the lower one a bit more (no reason I can particularly articulate)

Me too, perhaps it's because the pusher fills up the frame a bit more.

> For the macro, I think I would use something like upper one, but maybe make the charges a bit smaller and include some iconic force arrows?

I really like the idea of adding iconic force arrows! I'll mock up some options.

**Comment by arouinfar** [comment]
Started with the top Macro icon and reduced the size of the charges by 10%, then added iconic vectors.  I mocked up a few options and then realized the arrows pointed in the wrong direction, but we could instead change it so that both charges are positive (or negative).

<img width="626" alt="screen shot 2017-09-07 at 11 29 11 am" src="https://user-images.githubusercontent.com/8419308/30176713-b4a4ab7c-93c0-11e7-8a6d-f543bcb64bd6.png">

I quite liked option (4), so flipped the arrows around, and it still works pretty nicely.

<img width="291" alt="screen shot 2017-09-07 at 11 37 58 am" src="https://user-images.githubusercontent.com/8419308/30176855-0973db82-93c1-11e7-9cd3-34ed8aa55d1c.png">

My vote would be for option (5). @ariel-phet if you like options (1)-(4), I can mock it up with two positive (or negative) charges or try flipping/staggering the arrows, instead.

**Comment by ariel-phet** [comment]
I think I dig option (5) as well.

**Comment by arouinfar** [comment]
@jessegreenberg @mbarlow12 here are the screen/navbar icons

**Comment by arouinfar** [comment]
@jessegreenberg @mbarlow12 here are the icons we've decided on. The navbar icons are identical to the screen icons (just scaled down). I think these would be relatively straightforward to implement in code once we get the finalized pusher asset. I'd also be happy to provide the assets, if that's what you'd prefer. 


<img width="607" alt="screen shot 2017-09-07 at 1 35 14 pm" src="https://user-images.githubusercontent.com/8419308/30181739-8860bebe-93d1-11e7-8996-e14a8c2f518f.png">

**Comment by mbarlow12** [comment]
@arouinfar For the above icons, sending the separate pngs would be the easiest on our end. Thanks!

**Comment by arouinfar** [comment]
@mbarlow12 I've emailed you the screen icon assets.

**Comment by mbarlow12** [comment]
Images and license details added in last commit. @arouinfar or @ariel-phet, can one of you review the license info? Thanks.

**Comment by arouinfar** [comment]
Icons look good @mbarlow12. License info generally looks good, I'd update the notes to:
`macro_screen_icon.png` created by Amy Rouinfar
`atomic_scale_screen_icon.png` created by Cheryl McCutchan

**Comment by mbarlow12** [comment]
Thanks! Closing.
