### ISSUE TITLE
reset all doesn't reset the whole simulation

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/coulombs-law#15]
I noticed that charge values and some of the check boxes aren't properly reset.  @mbarlow12 could you please look into this?

**Comment by jessegreenberg** [comment]
Actually, it looks like charge is getting reset, but the intermediate Properties in the number controls aren't.

**Comment by mbarlow12** [comment]
Reset function added to ChargeControl. Now the reset button calls this on each charge control as well. Closing.
