### ISSUE TITLE
Coulombs Law Images

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/coulombs-law#2]
@arouinfar No rush on this item at all yet. We're looking for the pushing counterparts to add to the existing list of puller images. Let @jessegreenberg or me know if you have any issues. Thanks!

**Comment by arouinfar** [comment]
@mbarlow12 @jessegreenberg we can use the pushers from FAMB.

**Comment by jessegreenberg** [comment]
@arouinfar I would recommend a new set of images if possible.  The pushers in FAMB have a different color and shading than the pushers in GFL, moving from pushing to pulling in coulombs-law with the different types of pushers might look strange.

**Comment by arouinfar** [comment]
Excellent point @jessegreenberg. However, I think the pushers in FAMB are a bit newer and more in line with our modern aesthetic. I would recommend updating the GFL-pullers to match the style of the FAMB-pushers, instead. The updated pullers would then propagate to all inverse-square-law sims.

I'll work with our graphic artist to create updated assets.

**Comment by jessegreenberg** [comment]
Sounds great @arouinfar, thanks!  For the smooth animation, FAMB uses 30 images for the pusher, currently 15 images are used for the GFL pullers.

**Comment by arouinfar** [comment]
Good to know @jessegreenberg!

**Comment by ariel-phet** [comment]
@arouinfar would probably be good to get Cheryl involved at this point and also get some mockups of pullers built of atoms and the "hair standing on end" idea

**Comment by arouinfar** [comment]
Artwork is being tracked in https://github.com/phetsims/tasks/issues/834. Unassigning myself for now.

**Comment by mbarlow12** [comment]
Closing.
