### ISSUE TITLE
Adjust precision of Show Values

### ISSUE THREAD

**Issue by arouinfar** [phetsims/coulombs-law#23]
@jessegreenberg @mbarlow12 as discussed in today's design meeting, we'd like to make some adjustments to the number of digits being displayed with "Show Values".

Scientific Notation: 
- [x] If last digit is a zero, show it (currently being suppressed)
- [x] Hide "x10^0", because it looks a bit odd and wouldn't generally be written that way

Standard Notation:
- [x] For Macro, show 3 decimal places.
- [x] For Atomic, show 9 decimal places.

**Comment by mbarlow12** [comment]
Padding with zeroes handled in https://github.com/phetsims/inverse-square-law-common/commit/4c255d36a8620615324c4e189c764320ccb8e136.

**Comment by mbarlow12** [comment]
@jessegreenberg made the necessary updates to ScientificNotationNode in https://github.com/phetsims/scenery-phet/commit/bfa18745e03b7022d6f5ddc6627cf2540d489624.  This allow for the display of trailing zeroes when in scientific notation.

Closing.
