### ISSUE TITLE
Scale bar pixel polishing

### ISSUE THREAD

**Issue by arouinfar** [phetsims/coulombs-law#24]
During last week's design meeting, we decided that the scale bar could use some more visual weight (increase line weight and font size, use 10 pm on Atomic Scale). We also decided to add a pm to m conversion factor to the Atomic screen, because pm may be unfamiliar to the intended audience.

I've mocked up an updated scale bar to compare to [dev.5](http://www.colorado.edu/physics/phet/dev/html/coulombs-law/1.0.0-dev.5/coulombs-law_en.html). How does it look @ariel-phet? Should I bump up the font a bit more?

![screen shot 2017-09-05 at 12 50 07 pm](https://user-images.githubusercontent.com/8419308/30077344-cb4d4246-9238-11e7-9a1f-70af844cbcb3.png)
![screen shot 2017-09-05 at 12 50 16 pm](https://user-images.githubusercontent.com/8419308/30077347-cc58c020-9238-11e7-8377-87dd5d62394e.png)

**Comment by ariel-phet** [comment]
@arouinfar I think you could bump up the font a bit more.

The thickness of the double headed arrow seems good, however, I would make the vertical lines at each end of the double headed scale arrow significantly taller vertically. At least double or triple their current vertical size.

**Comment by arouinfar** [comment]
@ariel-phet thanks for the feedback. I bumped up the length of the vertical lines 2.5x, which looks about right to me. Also bumped all the font up a bit. Earlier, the pm conversion factor was 2pt smaller than the scale bar text, but included a version with it the same size. When they're the same size, I think the conversion factor competes a bit with the scale bar, but perhaps that's not so undesirable.

<img width="1023" alt="screen shot 2017-09-05 at 6 07 10 pm" src="https://user-images.githubusercontent.com/8419308/30088718-4c5b207a-9265-11e7-8c26-98205f35df9c.png">
<img width="1023" alt="screen shot 2017-09-05 at 6 07 26 pm" src="https://user-images.githubusercontent.com/8419308/30088719-4c5c80a0-9265-11e7-9a76-4fd85a124786.png">
<img width="1025" alt="screen shot 2017-09-05 at 6 10 02 pm" src="https://user-images.githubusercontent.com/8419308/30088764-8b125ca2-9265-11e7-80c7-c62f3f875efe.png">

**Comment by ariel-phet** [comment]
@arouinfar vertical height looks good now

I would go with the 3rd mockup but actually bump up the "10 pm" font a bit. I like how in the second mockup more emphasis is on the scale bar but the conversion factor just seems too small (hard to read the "-" sign in the exponent).

**Comment by arouinfar** [comment]
@ariel-phet I bumped up the scale bar font to 18pt for both screens. Looks about right to me.

<img width="1023" alt="screen shot 2017-09-06 at 5 09 12 pm" src="https://user-images.githubusercontent.com/8419308/30138560-3506e9e2-9326-11e7-8103-371d90254fec.png">
<img width="1024" alt="screen shot 2017-09-06 at 5 09 27 pm" src="https://user-images.githubusercontent.com/8419308/30138559-3505cf08-9326-11e7-952a-ab07f34a35a3.png">

**Comment by ariel-phet** [comment]
@arouinfar agreed, looking good!

**Comment by arouinfar** [comment]
Thanks @ariel-phet! 

@jessegreenberg @mbarlow12 the mockups for the updated scale bar can be found in https://github.com/phetsims/coulombs-law/issues/24#issuecomment-327636734.

* "1 cm" and "10 pm" text is 18 pt
* "1 picometer (pm) = 1x10^-12 m" is 16 pt
* Double-headed arrow stroke weight is 3 pt
* Vertical lines sandwiching the arrow have a stroke weight of 2 pt and length of 15 px

**Comment by jessegreenberg** [comment]
Looks great @arouinfar! Removing my assignment.

**Comment by mbarlow12** [comment]
@arouinfar feel free to check the latest changes to master when you have a chance. Thanks.

**Comment by arouinfar** [comment]
Looks great @mbarlow12!

@ariel-phet would you also like to review?

**Comment by ariel-phet** [comment]
Looks great! closing

**Comment by arouinfar** [comment]
@mbarlow12 when reviewing projector mode on master, I noticed that there's an "m" missing from the end of the conversion factor on the Atomic Scale Screen. It should read "1 picometer (pm) = 1x10^-12 m".
![image](https://user-images.githubusercontent.com/8419308/31101583-a2ba38e4-a78b-11e7-8e4d-3c522ae62ed4.png)

**Comment by mbarlow12** [comment]
Thanks for spotting that @arouinfar—fixed now.
