### ISSUE TITLE
Scientific notation should have constant precision

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/coulombs-law#28]
Could potentially be fixed with #23, so maybe that issue should be looked at first, but there is a bug in the value readout for scientific notation.  The precision changes when the hundredths decimal is zero:
![1](https://user-images.githubusercontent.com/6396244/30123190-6c582358-92ee-11e7-8efb-04eb950b009f.PNG)
![2](https://user-images.githubusercontent.com/6396244/30123193-6e3827d6-92ee-11e7-91e2-aeec121c10fd.PNG)

@mbarlow12 could you please take a look?

**Comment by mbarlow12** [comment]
I added a check for the length of the mantissa after the decimal. If it's less than 2 (we can also set that value through options if desired), we pad it out with zeroes so that -3.2 becomes -3.20.  

Closing.

**Comment by mbarlow12** [comment]
To be handled by changes in ScientificNotationNode. See https://github.com/phetsims/scenery-phet/issues/334.

**Comment by mbarlow12** [comment]
@jessegreenberg fixed in https://github.com/phetsims/scenery-phet/commit/bfa18745e03b7022d6f5ddc6627cf2540d489624.
