### ISSUE TITLE
Make the radii of the atomic charges smaller, move labels down a little

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/coulombs-law#29]
Came up during design meeting - it  was requested to make the radii of the charges in the atomic screen ever so slightly smaller.  I have 5% written down in my notes.

At the same time, it was also requested that the q1 and q2 labels be moved down a little bit farther in this screen.

Assigning to @mbarlow12.

**Comment by mbarlow12** [comment]
Closing for now—we can reopen if they require additional adjustment.
