### ISSUE TITLE
Add some space between the 100 and the end of the ruler in Atomic screen

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/coulombs-law#30]
In design meeting, it was requested that we add a little more space between the end of the ruler and the "100" label in the atomic screen.  This will require us to add more padding on both sides, but that seems fine. @mbarlow12 could you please take a look?

**Comment by mbarlow12** [comment]
Do we need to add padding only to the 100 side? The RulerNode doesn't have an option to differentiate right and left insets, and we'd have to alter the way it draws the ticks in order to allow it.

Adding the padding to both sides, on the other hand, is very straightforward. Thoughts?

**Comment by jessegreenberg** [comment]
> Adding the padding to both sides, on the other hand, is very straightforward. Thoughts?

That sounds great to me @mbarlow12.

**Comment by mbarlow12** [comment]
Handled in above commits. Closing.
