### ISSUE TITLE
Create projector mode

### ISSUE THREAD

**Issue by arouinfar** [phetsims/coulombs-law#32]
Since this sim has a black background, we'll need a projector mode. Generally, we should make the background white and the play area text/vectors black. Adding a black stroke around the charges will also be necessary since when the charge is small, the color won't contrast very well against a white background.

In https://github.com/phetsims/charges-and-fields/issues/140, it came to our attention that many teachers use a print setting that turns the black background into white. So long as there isn't a performance hit, we could add a black stroke around the white elements in the play area including:
* force strings
* q labels
* force vectors

In projector mode, these strokes should probably flip to white.

**Comment by arouinfar** [comment]
One more thought -- if the ruler and panels don't already have a black stroke, it would be good to add one to support better contrast for both printing and projector mode.

**Comment by mbarlow12** [comment]
When using that print setting, is it only the background that turns white, or are other elements on the page/screen also converted? E.g. might black arrow stroke be converted as well?

**Comment by arouinfar** [comment]
Good question @mbarlow12. I think the print setting applied to black backgrounds only, but I don't have any experience using such a setting. @pixelzoom are you familiar with the setting the user in https://github.com/phetsims/charges-and-fields/issues/140 was using?

**Comment by pixelzoom** [comment]
@arouinfar asked:
>  @pixelzoom are you familiar with the setting the user in phetsims/charges-and-fields#140 was using?

All of the information that I have from the user is in https://github.com/phetsims/charges-and-fields/issues/140#issue-257086959.  You might try asking him specific questions in https://groups.google.com/forum/#!topic/developing-interactive-simulations-in-html5/h7qeZ5LuIdM. Or I can send you his direct email address, if you prefer.

**Comment by pixelzoom** [comment]
I sent the user's email address to @arouinfar and @mbarlow12 via Slack.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. I've emailed the user, and I'll report back when he replies.

**Comment by arouinfar** [comment]
@mbarlow12 here's a print preview of Charges and Fields with the added black stroke around the arrows. Seems like the printer (or at least some printers) would be able to distinguish between the black background and the black stroke.
<img width="639" alt="screen shot 2017-09-19 at 11 09 23 am" src="https://user-images.githubusercontent.com/8419308/30605790-b315c5c8-9d2c-11e7-992a-cbab597a83cb.png">

Let's go ahead and proceed with adding the black stroke around the force strings, q labels, and force vectors in normal mode. In projector mode, these strokes can switch to white (otherwise the elements may look too bold).

**Comment by mbarlow12** [comment]
@arouinfar I ran into a bit of an issue with the stroke around the text. It appears that the default is to draw the stroke on the inside of the given element, which makes sense in order to keep the outer edges consistently placed.

<img width="892" alt="screen shot 2017-09-21 at 9 48 19 am" src="https://user-images.githubusercontent.com/5711147/30705324-5ebe5aa8-9eb2-11e7-8cb8-23fd9e68f2aa.png">

If we increase the font size, we may run into some weird spacing issues. One idea might be adding a square background just around the labels; however, I don't know if a printer would render that white as well. Do you or @jessegreenberg have any thoughts?

**Comment by jessegreenberg** [comment]
@mbarlow12 I can't think of a great solution to this.  Have you tried bumping up the font weight for the arrow labels? Would have to be changed when switching to projector mode so the black text doesn't look  too thick.

But since we have added a projector mode where the text changes to black on a white background, what is the benefit of adding a stroke around the text?

**Comment by jessegreenberg** [comment]
> Would have to be changed when switching to projector mode so the black text doesn't look too thick.

Or changed to white, which was originally suggested by @arouinfar.

**Comment by pixelzoom** [comment]
I would punt on stroking text.

**Comment by arouinfar** [comment]
@jessegreenberg originally, the idea was to add a stroke around the white elements as a fallback for those who print the sim, but haven't found Projector Mode.

@mbarlow12 thanks for experimenting with the stroked text! After seeing the results in https://github.com/phetsims/coulombs-law/issues/32#issuecomment-331200253, I agree with @pixelzoom. Let's remove the stroke around the text.

**Comment by mbarlow12** [comment]
While tinkering with the labels, I noticed that the small charge labels (q1, q2) create a drop shadow by duplicating the text and adding an offset. We could do the same thing with a heavy font weight to create a background/border of sorts for the text.

I'll try to ensure that it's only conditionally drawn based on the projector mode.

**Comment by mbarlow12** [comment]
Forget what I said above—there doesn't appear to be a way to both alter the weight & size of the text and condense the spacing between then so that everything's aligned properly. Going with the original punting plan.

**Comment by mbarlow12** [comment]
Closing.

**Comment by arouinfar** [comment]
Looks good on master @mbarlow12!
