### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/coulombs-law#34]
Per the Code Review Checklist, we can track the sim's credits here prior to publishing.

**Comment by arouinfar** [comment]
Lead Designer: Amy Rouinfar
Team: Amy Hanson, Ariel Paul, Kathy Perkins
Devs: Michael Barlow, Jesse Greenberg (?)
Graphic Arts: Mariah Hermsmeyer, Cheryl McCutchan
