### ISSUE TITLE
Landing screen focus highlights

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/coulombs-law#38]
In Safari and FF, we're seeing strange behavior with the focus highlights from the landing page/screen selection. Not sure yet if this is specific to this sim only or to all multiscreen a11y sims.

Safari:
In both the regular sim and the a11y view, the focus highlight seen on the landing page lingers. 
<img width="674" alt="screen shot 2018-01-11 at 2 33 15 pm" src="https://user-images.githubusercontent.com/5711147/34848564-793c241e-f6dc-11e7-9fdf-890cf2f07772.png">
<img width="672" alt="screen shot 2018-01-11 at 2 33 33 pm" src="https://user-images.githubusercontent.com/5711147/34848571-82593226-f6dc-11e7-8b46-d025aafa13d2.png">
Tabbing in either direction correctly blurs focus and moves it to the appropriate element. Once focus is lost from the lingering highlight, it cannot be regained again by the user.

Firefox:
In the regular sim, FF appears to exhibit identical behavior to Safari. The highlight simply lingers and can be blurred on tab interaction. However, in the a11y view, it appears that both landing page highlights still exist and can control the screen selection. The user can tab between them even after first moving focus to one of the sim's nodes.

Additionally it appears that there are focusable elements from both screens that are bleeding through. Cycling through all elements reveals several blank and repeated highlights before returning to the originally focused element (e.g. the address bar).

**Comment by mbarlow12** [comment]
@jonathanolson I _think_ this issue lies in joist or scenery. Do you have time this week to pair up and work on it?

**Comment by jonathanolson** [comment]
Sure, what time works well for you?

I took a brief look, and it looks like it still thinks the button on the homescreen is focused. Hackily tested with:
```js
setInterval( function() {
  console.log( phet.scenery.Display.focus && phet.scenery.Display.focus.trail.toPathString() )
}, 500 );
```
which continues to print `HomeScreenView/HBox/ScreenButton` in the buggy state (focus highlight for the homescreen button over another screen).

Not sure how switching screens is supposed to change the focus, are you familiar with the desired behavior?

**Comment by mbarlow12** [comment]
@jonathanolson Thanks for the feedback. I'll be working all day tomorrow, and @jessegreenberg and I were planning to tackle this in the AM.

I'd suggested pairing as I'm still pretty fuzzy on the inner workings of the scenery and display, but if there are other issues that might be more instructive, perhaps those might be better to pair on.

**Comment by jonathanolson** [comment]
I'll be available tomorrow, but I have some other collaboration scheduled at 10am. I'll be able to let you know tomorrow if I can help out before that, or if it would need to be after.

**Comment by jessegreenberg** [comment]
@mbarlow12 and I worked on this today. It turns out that Chrome is the only browser to blur the  active element if an ancestor gets hidden. If a descendant of a hidden element has focus, it is now blurred. Verified on Firefox and IE11, but @mbarlow12 could you please review the commit and make sure it works in Safari?

**Comment by mbarlow12** [comment]
@jessegreenberg Issue is fixed for standard screens. However, there's a lot of strange behavior in the a11y view—yet that may not be an issue since that's more for development. I'll create a new issue to track.
