### ISSUE TITLE
Adjust min/max threshold for figures

### ISSUE THREAD

**Issue by arouinfar** [phetsims/coulombs-law#39]
When reviewing #27, I noticed that the figures could be a bit more responsive at the extremes.

At the default values, the figure appears to be [figure_pull_1](https://github.com/phetsims/inverse-square-law-common/blob/master/images/figure_pull_1.png)/ [figure_pull_atomic_1](https://github.com/phetsims/inverse-square-law-common/blob/master/images/figure_pull_atomic_1.png), so decreasing the force does not show any apparent change in the figure's stance. 

On Atomic Scale, there is a slightly larger range of forces that can go off-screen, as compared to Macro. (Partly due to the user's ability to get the charges closer to one another.) At the minimum distance, the figure takes the deepest stance for any charge combination greater than 1/2 e. 

I think it would be a helpful visual cue if there was a bit more resolution at the lower and upper ends of the force range. The threshold for figure_1 could be a bit lower (on both screens) and the threshold for figure_31 could be a bit higher (on Atomic Scale). That way, students may still see the figure's stance move a bit, even when the vectors themselves are too extreme for a change in their magnitude to be noticeable. 

I realize there will always be some degree of saturation where the force increases/decreases but the figure doesn't appear to change, but I would like to reduce the range where saturation occurs.

**Comment by mbarlow12** [comment]
@arouinfar I'm not sure I fully understand what you're looking for here. Could we take a few minutes today or tomorrow to discuss?

**Comment by arouinfar** [comment]
After speaking with @mbarlow12, I've learned that the mapping between the force and the figure is a bit complicated, particularly because the force can be positive or negative.

We spent some time adjusting `PULL_RANGE_MULTIPLIER`, and it looks like that may give me the results I'm looking for. I will experiment a bit with my local copy, and recommend a value to @mbarlow12.

**Comment by arouinfar** [comment]
@mbarlow12 let's go with `PULL_RANGE_MULTIPLIER` =  1/50.

**Comment by mbarlow12** [comment]
Thanks! Fixed in above commit. Closing.
