### ISSUE TITLE
a11y view focus highlight behavior

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/coulombs-law#40]
In FF and Safari, there a lot of lingering and misplaced focus highlights. These are likely a result of the iframe implementation of the sim on this screen. Since a11y view isn't part of our production releases, this may not be an problem. Seems useful to document these issues as they may appear in other contexts where the display (i.e. iframe) is similar.

**Comment by jessegreenberg** [comment]
Its like none of the hidden elements in the a11y-view are removed from focus order. @mbarlow12 could you please see if this is an issue in the other iframe test? I think the iframe test is generated during build so after running `grunt` it can be found in http://localhost:8080/coulombs-law/build/phet/coulombs-law_en_iframe_phet.html?accessibility

**Comment by jessegreenberg** [comment]
It is *not* a problem in *_iframe_phet.html* for FF, I am not able to test Safari. So it looks like this is just an issue with the a11y-view which is very strange.

**Comment by mbarlow12** [comment]
Confirmed that there's no bug in the iframe on Safari—just the a11y-view issue.

**Comment by jessegreenberg** [comment]
Great, thanks @mbarlow12. I am going to move this issue to chipper because it impacts all sims that use the a11y-view.
