### ISSUE TITLE
In Safari I don't see pressed Arrow style

### ISSUE THREAD

**Issue by terracoda** [phetsims/coulombs-law#44]
@jessegreenberg and @mbarlow12, just noticed that I only see the nice pressed arrow styles when using Shift plus the Arrow key to move the Charge 1 and Charge 2 sliders.

Is that intentional?

Using Safari 11.0.2 with and without VO on Mac High Sierra 10.13.2.

**Comment by jessegreenberg** [comment]
@terracoda that is intentional. Those buttons are called the "Tweaker" buttons and are only pressed when stepping the slider by the smallest value with shift. It is a little different for this sim because the shift key doesn't change the step size for the slider.

**Comment by terracoda** [comment]
Ok, cool. Good with that. Closing.
