### ISSUE TITLE
Navigating to home screen ends keyboard navigation

### ISSUE THREAD

**Issue by ghost** [phetsims/coulombs-law#49]
Small issue. If you're in the Macro Scale screen or the Atomic Scale screen and you navigate to the Home screen, then keyboard navigation ends. This happens in FF, Chrome, Edge. Wondering if we want to change this. This is for phetsims/QA/issues/87 but also for any sim with keyboard navigation.

**Comment by jessegreenberg** [comment]
> then keyboard navigation ends.

@lmulhall-phet can you please clarify? Does this mean "further keyboard navigation is impossible" or "focus is nowhere on the home screen, but I can tab to the first focusable element?".

**Comment by ghost** [comment]
The latter, hence the warning "small issue."

**Comment by jessegreenberg** [comment]
Ok, thanks. I am curious as to why this doesn't happen when leaving the home screen.

**Comment by ghost** [comment]
> leaving the home screen

@jessegreenberg what do you mean?

I just noticed that using keyboard navigation to enter either the Macro or Atomic screen "ends" (using definition from above) keyboard nav. Is this what you mean?

**Comment by jessegreenberg** [comment]
Well for me, the behavior is this (at least for Chrome):

- When pressing  enter on screen button in home screen, focus goes away. Pressing tab makes focus go to first focusable  element in sim. This is what I would expect.
- When pressing enter on "Home" button in nav bar, focus goes  away. Pressing tab makes focus go to Chrome navigation bar, not fist home screen button, which is strange.

**Comment by ghost** [comment]
The second bullet point is not an issue in Safari, FF, or Edge, but I do experience it in Chrome.

**Comment by jessegreenberg** [comment]
Thanks @lmulhall-phet, confirmed.

**Comment by jessegreenberg** [comment]
@emily-phet can you please review this issue and assign priority/severity? This is partly a bug and partly a design question.

Design question: I have assumed that focus should go to the top of the document when a new screen is opened. This way someone reading through the active screen with a screen reader will start at the top rather than the first focusable element. I believe the same is important for the home screen. Is this correct?

Bug: For some reason, when navigating to the Home screen, chrome moves focus up to the address bar rather than the top of the document.

**Comment by mbarlow12** [comment]
@jessegreenberg and I tried some sleuthing for this issue to no avail. As far as we can tell, Chrome is receiving the exact same DOM and data as FF and Safari. This issue could potentially take a very long time to track down and could be a bug in the Chrome browser.

@zepumph did the initial work to make the navigation bar and home screen buttons accessible/operable, so he might have some insight. @zepumph let us know if you have time to look into this. Feel free to unassign yourself if you don't.

For what it's worth, I also confirmed this behavior in Plinko Probability.

**Comment by zepumph** [comment]
It will be at least until the week of March 5th before I will be able to look into this, unless we talk about it at the dev meeting tomorrow.

**Comment by mbarlow12** [comment]
@jonathanolson Had a nice suggestion. When returning to the home screen, the screen which the user was just on is still highlighted, so simply set focus on that button. This diverges from the behavior @jessegreenberg mentioned in https://github.com/phetsims/coulombs-law/issues/49#issuecomment-363518012, but it might offer a clean workaround for the time being.

**Comment by jessegreenberg** [comment]
We discussed 2/23/18 accessibility meeting - we like @jonathanolson's recommendation. We will look into  returning focus to the selected screen button. At this time it is not worth the time to figure out why Chrome is behaving in this way.

**Comment by jessegreenberg** [comment]
@mbarlow12 can we pair on this sometime soon?

**Comment by mbarlow12** [comment]
Sure thing. Wanna tackle it this afternoon? I'm free all day.

**Comment by mbarlow12** [comment]
Fixed in the above commit, yet exposed some new erroneous behavior. See https://github.com/phetsims/coulombs-law/issues/55 for new issue.

**Comment by jessegreenberg** [comment]
Above commit looks good @mbarlow12, but just a friendly reminder to build and run fuzz tests before pushing to common code. The above commit fixes a lint error that popped up in CT.
