### ISSUE TITLE
Sim is vulnerable to xss

### ISSUE THREAD

**Issue by phet-steele** [phetsims/coulombs-law#5]
Run the sim with `?stringTest=xss` to be redirected. Running on current master (4/4 1:30 PM).

**Comment by jessegreenberg** [comment]
@phet-steele any other sims exhibiting this?

Also, this was found with automated testing?

**Comment by phet-steele** [comment]
> @phet-steele any other sims exhibiting this?
> 
> Also, this was found with automated testing?

Double yes.

**Comment by jessegreenberg** [comment]
Possibly a vulnerability with HTMLText? @phet-steele said that gene-expression-basics also had this issue does it use HTMLText?

**Comment by mbarlow12** [comment]
Maybe, but I'm pretty confused as to how it's achieving the redirect. Do we
have any info on the vulnerability?

**Comment by jessegreenberg** [comment]
@mbarlow12 we are hitting this from a new automated test which can be run with query parameter `?stringTest=xss`.  If you are curious about additional details, they can be found in chipper/initialize-globals.js.

**Comment by jonathanolson** [comment]
Fixed with RichText in commit above.
