### ISSUE TITLE
Lower number of decimals shown on macro screen / regular notation?

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/coulombs-law#50]
I showed this dev off to a perspective user today, and had a thought.

On the macro screen, when scientific notation is unchecked, there seems to be many more decimal places listed than is really necessary (unless somehow I am missing a setting for very small forces). Seems like it could be reduced to just x.xxx and would still have good precision for plotting. (Note, I would keep the model value highly accurate, and just make the change on the displayed value).

**Comment by kathy-phet** [comment]
@arouinfar - Can you review this suggestion?

**Comment by arouinfar** [comment]
@kathy-phet it looks like we already made this request in #23, but somehow got overlooked (or later reverted?). @mbarlow12 can you investigate?

**Comment by mbarlow12** [comment]
Thanks for the heads up @arouinfar. I found the change I made initially, and I have no idea when/where it was deleted. Fixed on master.
