### ISSUE TITLE
branch: augmented-arrows

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/coulombs-law#51]
Identified by `print-branches.sh`.  Looks like lots of hands in this branch - @mbarlow12 @zepumph @jessegreenberg @jonathanolson one of you please describe.

**Comment by jessegreenberg** [comment]
This branch was for https://github.com/phetsims/coulombs-law/issues/27, and has been merged into master and should be pruned.

**Comment by jessegreenberg** [comment]
Deleted, closing.

**Comment by zepumph** [comment]
Should be re-deleted as part of phetsims/special-ops#198

**Comment by zepumph** [comment]
Deleted
