### ISSUE TITLE
branch: large-arrows

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/coulombs-law#52]
Identified by `print-branches.sh`.  Looks like lots of hands in this branch - @mbarlow12 @zepumph @jessegreenberg @jonathanolson one of you please describe.

**Comment by jessegreenberg** [comment]
Last commits in this branch indicate this was for #27 which has been closed, I believe this branch can be pruned. @mbarlow12 is that correct?

**Comment by mbarlow12** [comment]
Yup. Closing.

**Comment by zepumph** [comment]
Should be re-deleted as part of phetsims/special-ops#198

**Comment by zepumph** [comment]
Deleted
