### ISSUE TITLE
Keyboard nav requires extra tab after mouse click back to home screen

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/coulombs-law#55]
The recent commits to fix https://github.com/phetsims/coulombs-law/issues/49, led to another issue where using the mouse to navigate back to the home screen results in an extra tab interaction to return focus to the screen buttons.

The focus is also always placed on the first screen instead of the screen the user came from. And this happens in all browsers.

@jessegreenberg and I think it's likely due to the fact that the blurred button is technically still focusable while one of its parents is not. By checking all parents in the scene graph, we can better handle the tab behavior in this scenario.

**Comment by jessegreenberg** [comment]
@mbarlow12 and I worked on this today, the theory and fix mentioned in the original  ticket were correct. Fixed in the above commit.  Closing.
