### ISSUE TITLE
Keyboard Navigation Dialog

### ISSUE THREAD

**Issue by arouinfar** [phetsims/coulombs-law#58]
Looks like the sim is keyboard navigable, but we don't yet have a dialog.

**Comment by arouinfar** [comment]
I modeled the dialog on GFLB (https://github.com/phetsims/gravity-force-lab-basics/issues/29) but Coulomb's Law has some notable differences, including the ruler and sliders to change charge magnitude (rather than numberPicker).

The latter difference makes things a bit tricky, as the sim has two sets of sliders -- the visual sliders to change charge magnitude and the spheres themselves. I had considered collapsing all four sliders into a generic "Slider Controls" but there's a few reasons I decided against it:

* The spheres are not visual sliders, so the "Move Spheres" title gives things a bit more context.
* Home/End is better described as left/right for the spheres and min/max for charge sliders.

![image](https://user-images.githubusercontent.com/8419308/40740043-fc37e8c2-6404-11e8-83d2-2d785f5cd0de.png)

Tagging for design meeting to discuss in conjunction with #43.

**Comment by arouinfar** [comment]
Since the static descriptions refer to the objects as "charges",  I've updated the dialog

![image](https://user-images.githubusercontent.com/8419308/40933604-393b88f8-67ef-11e8-9963-f0bb3faaddfd.png)

@terracoda can you review?

**Comment by terracoda** [comment]
@arouinfar, we used "Move Spheres" and "Change Mass" for headings in GFLB.

Does "Move Charged Spheres" and "Change Charge" would work here?

**Comment by terracoda** [comment]
Or even, "Move Spheres" and "Change Charge"?
If so, it could follow GFLB a bit more closely.

**Comment by terracoda** [comment]
Since, the Charge sliders are horizontal sliders, and not number spinners with up/down arrows, we could focus on vertical movement all the way through if you think that is important.

**Comment by terracoda** [comment]
@arouinfar, is "increase" and "decrease" charge better here or not?

**Comment by arouinfar** [comment]
Thanks for the feedback @terracoda. 

In GFLB, the headings refer to the objects as "spheres", but in CL they are "charges", so I think "Move Charges" is more analogous. 

The "Change Mass" controls are numberPickers, but in CL they are sliders, so the title and controls reflect typical slider dialog content. If we want to "increase" or "decrease" the charge, we cannot use the standard slider dialog content (see #https://github.com/phetsims/gravity-force-lab-basics/issues/29#issuecomment-367104942).  Changing the title to "Change Charge" could work, as that's how the help text begins, though it would also be at odds with slider-specific content.

We could pretend the charge sliders are numberPickers, and format the dialog like this, however I think it makes a bit more sense to continue treating the charge sliders like sliders.

**Change Charge**
Increase charge [up]
Decrease charge [down]
Adjust in larger steps [pg up] [pg down]
Jump to minimum [home]
Jump to maximum [end]

**Comment by terracoda** [comment]
@arouinfar, I am looking at the content of CL and the dialog to make sure things are aligned content-wise...more to come.

**Comment by terracoda** [comment]
@arouinfar 
How about this for the dialog content?:
**H1: Keyboard Shortcuts**
**H2: Change Charge Positions**
- Move charge left or right with Arrow keys.
- Move in larger steps with Page Up and Page Down keys.
- Jump left with Home key.
- Jump right with End key.

**H2: Move Ruler**
Move ruler up, left, down, or right with Arrow keys or with letter keys W, A,S, or D.

**H2: Adjust/Change Charge Amount**
- Adjust/Change amount with left and right arrow keys, or up and down arrow keys.
- Adjust/Change in larger steps with Page Up and Page Down keys.
- Jump to minimum with Home key.
- Jump to maximum with End key.

**H2: General Navigation**
- Move to next item with Tab key.
- Move to previous item with Shift plus Tab key.
- Exit this dialog with Escape key.

**Comments/Questions:**
Note that wording for the _charge slider_ is the same as RIAW sliders, except for the word "amount" is used instead of "slider", which I think is useful here.
- @arouinfar, do you agree?

Alternatively, you could separate the _charge slider_ help text into increase and decrease **_if you want_ the interaction to be cued more like (big emphasis on if)** the number pickers in GFLB. Like this, for example:

- Increase charge with right or up and Arrow keys.
- Decrease charge with left or down arrow keys.
 
**Adding one more comment after posting:**
You might get away with "Move left or right with Arrow keys." instead of "Move charge left or right with Arrow keys." I personally, like the emphasis on "charge".

**Comment by terracoda** [comment]
@arouinfar, you might want to use "charge" instead of "amount". And in addition, you might want to add the word you choose into the bigger steps line:
- Adjust/Change amount/charge in larger steps with Page Up and Page Down keys.

I defer to you on this, and look forward to your comments.

**Comment by terracoda** [comment]
@arouinfar, and the content is in the A11y Design doc, if it easier to work there on this content.
https://docs.google.com/document/d/1z5ZdC75hdAftXJyfZgQKKgVUGTkKDbT4U2lQLLhZt1Q/edit#

**Comment by arouinfar** [comment]
Thanks @terracoda. I added some comments to the doc. My main concerns are with the H2's. I believe those should match the dialog content, and the doc seems to deviate from our conventions for previous dialogs.

**Comment by terracoda** [comment]
It's actually the headings that have the most flexibility of content. It's ideal to do the pedagogical cuing there, alone, if we can. In GFLB we adjusted the in the content as well for pedagogical reasons. 

If you feel there is no need here to adjust the content instructions for pedagogical cuing, that's fine.

**Comment by terracoda** [comment]
@arouinfar, I have added visual examples tot he design document, to clarify the differences between the visual content and the text-based content.

I think you can see how these different dialogs cue in slightly different ways.

**Comment by arouinfar** [comment]
@terracoda thank you for all of the mockups! I really like version 2. I think "Charge Amount" is a more descriptive than "Charge Controls" so I updated those H2's throughout the sim. I added a comment chain to the mockup for @terracoda to review.

![image](https://user-images.githubusercontent.com/8419308/41732045-39dbc696-753d-11e8-8384-cf8cdd80c0b3.png)

**Comment by arouinfar** [comment]
@terracoda and I have finalized the dialog and its [a11y content](https://docs.google.com/document/d/1z5ZdC75hdAftXJyfZgQKKgVUGTkKDbT4U2lQLLhZt1Q/edit?ts=5b2bd674#heading=h.96emyia66ao9).

@mbarlow12 the dialog is now ready for implementation. 
![image](https://user-images.githubusercontent.com/8419308/41735723-ac4a5cce-7547-11e8-8f41-0a95666d524b.png)

**Comment by jessegreenberg** [comment]
Discussed on 7/17/18, coulombs-law will be published first without a11y.  A11y will be included when we republish the simulation in a future minor release.

**Comment by arouinfar** [comment]
@mbarlow12 I saw the dialog up on master, and it's looking great!

**Comment by arouinfar** [comment]
The dialog is looking good in rc.1, so I think we can go ahead and close this issue.

**Comment by arouinfar** [comment]
For https://github.com/phetsims/QA/issues/210

@phet-steele pointed out the shift modifier was missing from the dialog. Originally, the arrow step size was 0.1 cm, making the shift modifier redundant. However, now that the arrow keys have been increased to 0.2 cm (see https://github.com/phetsims/gravity-force-lab-basics/issues/72), it makes sense to include the shift modifier in the dialog.

@mbarlow12 please add this to the Charge Positions section, right after `Move charges`:
* Move in smaller steps [Shift] + [left][right]

**Comment by mbarlow12** [comment]
@arouinfar good point! Totally overlooked that.

**Comment by mbarlow12** [comment]
Shift modifier line added in above commit on the 1.0 branch.

**Comment by arouinfar** [comment]
@mbarlow12 I'm not seeing it in master. I pulled inverse-square-law-common and coulombs-law. Is there something I overlooked?

**Comment by mbarlow12** [comment]
@arouinfar I just merged the changes to master. Should be all set on both master and the 1.0 branches!

**Comment by arouinfar** [comment]
Thanks @mbarlow12. I have one pixel polishing request.

The left/right arrows next to "Move charges" should be left-aligned with the other key icons. 
![image](https://user-images.githubusercontent.com/8419308/47449202-4f890b80-d77f-11e8-9c1d-00354378fa3b.png)

**Comment by mbarlow12** [comment]
@arouinfar thanks for the spot—fixed in master.

**Comment by mbarlow12** [comment]
New rc:
https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.4/phet/coulombs-law_en_phet.html

**Comment by arouinfar** [comment]
Looks great!

**Comment by KatieWoe** [comment]
Looks good on 1.0.0-rc.4
