### ISSUE TITLE
Default ruler step should be 1/10th cm and 1/10th pm

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/coulombs-law#59]
Requested by @arouinfar, the default step size for ruler dragging should be 1/10th of a cm in macro scale, 1/10th of a pm in atomic scale, and we should remove the fine grain control from shift key.

It is frustrating to remember that shift key is used to snap the ruler to the smallest grid size in the sim. And since the ruler has press and hold behavior to  quickly move it  out of the view, we don't get any benefit by having larger/smaller step sizes with shift key.

@mbarlow12 can you please work on this?

**Comment by jessegreenberg** [comment]
Oh, this is only a change for the keyboard dragging behavior.

**Comment by arouinfar** [comment]
Thanks for opening this issue @jessegreenberg.

The charges snap to 0.1 cm when moving them with the arrow keys, but the ruler snaps in 0.2 cm increments. It's quite easy to have a situation in which it's impossible to line up the ruler tick marks with the charges. For example:

![image](https://user-images.githubusercontent.com/8419308/40810947-9c913a16-64ec-11e8-9eab-ed963bc7fda3.png)

**Comment by mbarlow12** [comment]
New dev deployment:
https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-dev.17/phet/coulombs-law_en_phet.html

**Comment by arouinfar** [comment]
Looks great, thanks @mbarlow12!
