### ISSUE TITLE
Change Default Values on Macro Screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/coulombs-law#60]
In order to boost the default vector size, we decided to update the initial values to:

- [x] q1 = -4 µC
- [x] q2 = 8 µC
- [x] distance = 3 cm

![image](https://user-images.githubusercontent.com/8419308/40810721-ecd128f2-64eb-11e8-914d-45250264ec78.png)

**Comment by mbarlow12** [comment]
New dev deployment with the above changes:

https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-dev.17/phet/coulombs-law_en_phet.html

**Comment by arouinfar** [comment]
👍
