### ISSUE TITLE
Update Credits

### ISSUE THREAD

**Issue by Denz1994** [phetsims/coulombs-law#64]
Created during the review of Coulombs-Law in https://github.com/phetsims/coulombs-law/issues/63 so we don't forget to update credits as needed.

**Comment by arouinfar** [comment]
The design credits are up to date, but Amy Hanson's last name has been misspelled. It should be Hanson with an 'o'.

QA credits will undoubtably expand, so this issue should be reassigned to @KatieWoe when we move into testing.

**Comment by mbarlow12** [comment]
Changed Amy's last name and added a TODO for QA credits. Closing.

**Comment by arouinfar** [comment]
Since we're in RC, @KatieWoe should confirm the QA credits.

**Comment by KatieWoe** [comment]
@mbarlow12 please add Katie Woessner and Laura Rea please.

**Comment by mbarlow12** [comment]
See links for fixes:
https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.5/phet/coulombs-law_en_phet.html
https://github.com/phetsims/QA/issues/221

**Comment by KatieWoe** [comment]
Looks good @mbarlow12 
Edit: Actually, wait for this, incase more testers work on this rc.  Sorry about that.

**Comment by phet-steele** [comment]
QA credits should still be alphabetized by last name (like all of our other sims).

**Comment by arouinfar** [comment]
QA credits have been alphabetized and updated to add testers from rc.6 onwards.
