### ISSUE TITLE
Inconsistent screen names

### ISSUE THREAD

**Issue by Denz1994** [phetsims/coulombs-law#65]
As noted in #63:

> Do filenames use an appropriate prefix?

CLMacroScreen.js and CLAtomicScreen.js are inconsistent with the rest of the file names, which use the extend name of the sim (i.e. CoulombsLawGlobalOptionsNode.js). These file names should be changed @mbarlow12.

**Comment by mbarlow12** [comment]
Updated file names per @Denz1994 suggestion.
