### ISSUE TITLE
String file cleanup

### ISSUE THREAD

**Issue by Denz1994** [phetsims/coulombs-law#66]
It was advised by @phet-steele to alphebetize this list of strings in the respective .json files (phetsims/masses-and-springs#151). I am relaying this suggestion along to @mbarlow12 for `inverse-square-law-common-strings_en.json` and `coulombs-law-strings_en.json`.

Also, consider changing to screen.macroScale and screen.atomicScale. Currently, the file reads like this: 
```
 "screen.macro": {
    "value": "Macro Scale"
  },
  "screen.atomic": {
    "value": "Atomic Scale"
  },
```

**Comment by mbarlow12** [comment]
@Denz1994 thanks for passing along. I've made the changes; do you prefer closing issues you've opened?

**Comment by Denz1994** [comment]
You can close them @mbarlow12. They seem pretty straight forward.
