### ISSUE TITLE
WASD Translation

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/coulombs-law#71]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/210
The W, A, S, and D keys in the keyboard nav instructions do not seem to be translatable.  Should they be?
**Steps to reproduce:**
1. Use a stringTest query parameter, such as stringTest=rtl
2. Open the keyboard nav instruction dialog

**Screenshots:**
![wasd](https://user-images.githubusercontent.com/41024075/47043408-c9e7d900-d14a-11e8-9fee-4d6794515c82.PNG)

**Troubleshooting information (do not edit):**

<details>

Name: ‪Coulomb's Law‬:‪Coulomb's Law‬
URL: https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.1/phet/coulombs-law_en_phet.html?stringTest=double
Version: 1.0.0-rc.1 2018-10-16 17:37:35 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"7751fab5","branch":"HEAD"},"brand":{"sha":"1fd6682e","branch":"HEAD"},"chipper":{"sha":"fc5919bb","branch":"HEAD"},"coulombs-law":{"sha":"2b40b3e5","branch":"HEAD"},"dot":{"sha":"dcccfddd","branch":"HEAD"},"inverse-square-law-common":{"sha":"8cbef658","branch":"HEAD"},"joist":{"sha":"b12072c7","branch":"HEAD"},"kite":{"sha":"380cef53","branch":"HEAD"},"phet-core":{"sha":"4404c06b","branch":"HEAD"},"phet-io":{"sha":"a7436d70","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"534dc595","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"3372700d","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"09507f4d","branch":"HEAD"},"phet-io-wrappers":{"sha":"0a4a3153","branch":"HEAD"},"phetcommon":{"sha":"33aef589","branch":"HEAD"},"query-string-machine":{"sha":"9ae63aab","branch":"HEAD"},"scenery":{"sha":"f402eed4","branch":"HEAD"},"scenery-phet":{"sha":"dc31f4d9","branch":"HEAD"},"sherpa":{"sha":"0989d371","branch":"HEAD"},"sun":{"sha":"46ee1492","branch":"HEAD"},"tambo":{"sha":"fe63321c","branch":"HEAD"},"tandem":{"sha":"f9cfcc67","branch":"HEAD"}}

</details>

**Comment by phet-steele** [comment]
Last discussion of this that I remember was towards the end of https://github.com/phetsims/friction/issues/57.

**Comment by arouinfar** [comment]
Thanks @phet-steele!

In https://github.com/phetsims/friction/issues/57#issuecomment-350340501, @jessegreenberg said:
> I am not sure yet how we will support layouts like JCUKEN (russian keyboard in your link), keycodes could be very different. I think we should prevent i18n of keys until we decide to support different keycodes in the translation utility.

It seems (for now, at least) that letter keys should not be translatable. The keyboard dialog in Coulomb's Law seems appropriately translatable to me, so closing.
