### ISSUE TITLE
q1 and q2 labels change size

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/coulombs-law#72]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Firefox (only one so far)
**Problem description:**
For https://github.com/phetsims/QA/issues/210
Very minor, likely not high priority.  When moving the charges next to each other and away, the small q1 and q2 labels below the charges seem to shift size.  Only seen on firefox so far.  The video was made with showPointerAreas, but it is not necessary.
**Steps to reproduce:**
1. Go to the sim on firefox.
2. Seems to happen on both screens but is easier to see on Atomic Scale.
3 . Drag the right person up next to the left charge, drag it away, and repeat

**Screenshots:**
![size](https://user-images.githubusercontent.com/41024075/47046098-9d838b00-d151-11e8-9861-c9ad4f2de79f.gif)

**Troubleshooting information (do not edit):**

<details>

Name: ‪Coulomb's Law‬
URL: https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.1/phet/coulombs-law_en_phet.html?showPointerAreas
Version: 1.0.0-rc.1 2018-10-16 17:37:35 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
Language: en-US
Window: 1536x760
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"7751fab5","branch":"HEAD"},"brand":{"sha":"1fd6682e","branch":"HEAD"},"chipper":{"sha":"fc5919bb","branch":"HEAD"},"coulombs-law":{"sha":"2b40b3e5","branch":"HEAD"},"dot":{"sha":"dcccfddd","branch":"HEAD"},"inverse-square-law-common":{"sha":"8cbef658","branch":"HEAD"},"joist":{"sha":"b12072c7","branch":"HEAD"},"kite":{"sha":"380cef53","branch":"HEAD"},"phet-core":{"sha":"4404c06b","branch":"HEAD"},"phet-io":{"sha":"a7436d70","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"534dc595","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"3372700d","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"09507f4d","branch":"HEAD"},"phet-io-wrappers":{"sha":"0a4a3153","branch":"HEAD"},"phetcommon":{"sha":"33aef589","branch":"HEAD"},"query-string-machine":{"sha":"9ae63aab","branch":"HEAD"},"scenery":{"sha":"f402eed4","branch":"HEAD"},"scenery-phet":{"sha":"dc31f4d9","branch":"HEAD"},"sherpa":{"sha":"0989d371","branch":"HEAD"},"sun":{"sha":"46ee1492","branch":"HEAD"},"tambo":{"sha":"fe63321c","branch":"HEAD"},"tandem":{"sha":"f9cfcc67","branch":"HEAD"}}

</details>

**Comment by KatieWoe** [comment]
Edit: Upon further examination, it seems to be caused by dragging, not by being next to the other charge.  The size of the label is different during dragging compared to not being dragged.
Occurs on the labels above the vectors as well.

**Comment by mbarlow12** [comment]
I'm noticing that what seems to happen is if an object is dragged more than 1 increment, it will sometimes be redrawn a little shorter (for lack of a better term). Then when the dragging stops (not mouse released), the white fill takes up the appropriate space. It almost looks like during the drag, the text gets a tiny grey border that's then filled on dragging stopped.

@KatieWoe have you seen this in any other sims?

**Comment by KatieWoe** [comment]
Checking out the published version of https://phet.colorado.edu/sims/html/gravity-force-lab/latest/gravity-force-lab_en.html I see it there as well.  It seems to be a specific type of text though, as I didn't see it in things like Balancing Act with its mass label. @mbarlow12

**Comment by mbarlow12** [comment]
I noticed that Balancing Act only uses our `Text` type, while the super and subscripts in Coulomb's Law require the use of `RichText`.

@jessegreenberg or @jonathanolson is this a result of the `RichText` type, or is it more likely something in the CL implementation? Could we set up a time to pair on it in the next couple days?

**Comment by jessegreenberg** [comment]
I actually do see this in Balancing Act, see how the label shifts just a bit
![capture](https://user-images.githubusercontent.com/6396244/47366631-1b90e600-d6ac-11e8-9285-ca394c087e01.gif)

So it seems like a general issue with movable text in FF, and should probably be picked up in Scenery. Sorry I am too unfamiliar with Text to be of more help, so removing my assignment. But also assigning to @ariel-phet to help determine priority for investigating this issue.

**Comment by arouinfar** [comment]
@KatieWoe good attention to detail! Keep bringing issues like this to our attention.

I'll go ahead and throw in my 2 cents. Given that this is a scenery issue, and does not meaningfully affect sim interaction, I do not think this should be a blocking issue for Coulomb's Law. 

I'll leave it up to @ariel-phet to decide if this issue should be moved to scenery for further investigation.

**Comment by ariel-phet** [comment]
Not a blocking issue.

**Comment by jonathanolson** [comment]
Interesting, this looks the most similar to https://github.com/phetsims/scenery/issues/47. It used to be a very obvious quality switch with Firefox SVG-rendered text, where it had a higher-performance lower-quality version for "moving" text, and then once its heuristics determined it was "not moving" it got switched to a higher-quality (presumably lower-performance) version.

@ariel-phet, should I reopen that issue (and should this issue be closed?)

**Comment by ariel-phet** [comment]
@jonathanolson yes, please reopen that issue in scenery, close this one

Also notice in a sim like this one in dev, this is happening quite noticeably when you move the sliders. Still not a "blocking issue" but it would be nice to fix if is simple to fix

https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.0-dev.3/phet/resistance-in-a-wire_en_phet.html?supportsSound

**Comment by jonathanolson** [comment]
Reopened the common issue, closing this issue.
