### ISSUE TITLE
Unused string:  projectorMode

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/coulombs-law#73]
When building coulombs-law for https://github.com/phetsims/scenery-phet/issues/411, I noticed that it has an unused string

> Unused string: key=COULOMBS_LAW/options.projectorMode, value=Projector Mode

Code and the string for the projector mode option has  been moved to common code, which is why the string is unused.  I think this string was generally left in sims for compatibility with existing translations, but since this sim hasn't been deployed yet I think it can be removed. It may be nice to remove so we don't see the warning every time we build the sim from now on. If this string is removed it will need to be removed for both master and the RC branch. @mbarlow12 could you please take a look?

**Comment by mbarlow12** [comment]
@jessegreenberg the string has been removed and no longer raises a flag on build.

**Comment by jessegreenberg** [comment]
Great, thanks! Reassigning to you to make sure this change gets into the RC branch.

**Comment by mbarlow12** [comment]
Updates pulled into 1.0 in https://github.com/phetsims/coulombs-law/commit/9ca81f70a8f938f4d48cbd73b4893127efc86d6e.

**Comment by jessegreenberg** [comment]
Verified the warning is gone with 1.0 SHAs. Thanks! Going to go ahead and close
