### ISSUE TITLE
Zero times ten to the first power

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/coulombs-law#77]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/214. May be related to https://github.com/phetsims/coulombs-law/issues/12.
When force is zero and scientific notation is on, it reads 0.00x10^1.  It would seem to be more constant for it to say 0.00, as seen in screenshots below.  Or for it to say 0.00x10^0.
**Steps to reproduce:**
1. Go to either screen.
2. Make sure Scientific Notation is selected.
3. Set one charge at 0 charge

**Screenshots:**
![tentotheone](https://user-images.githubusercontent.com/41024075/48017287-2192b800-e0eb-11e8-984c-2e45ba01c01f.PNG)
![noten](https://user-images.githubusercontent.com/41024075/48017295-248da880-e0eb-11e8-8cec-e5b5f7298010.PNG)

Troubleshooting information (do not edit):

<details>

Name: ‪Coulomb's Law‬
URL: https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.4/phet/coulombs-law_en_phet.html
Version: 1.0.0-rc.4 2018-10-30 20:35:59 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"7751fab5","branch":"HEAD"},"brand":{"sha":"1fd6682e","branch":"HEAD"},"chipper":{"sha":"fc5919bb","branch":"HEAD"},"coulombs-law":{"sha":"46b9481c","branch":"HEAD"},"dot":{"sha":"dcccfddd","branch":"HEAD"},"inverse-square-law-common":{"sha":"aec59098","branch":"HEAD"},"joist":{"sha":"b12072c7","branch":"HEAD"},"kite":{"sha":"380cef53","branch":"HEAD"},"phet-core":{"sha":"4404c06b","branch":"HEAD"},"phet-io":{"sha":"a7436d70","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"534dc595","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"3372700d","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"09507f4d","branch":"HEAD"},"phet-io-wrappers":{"sha":"0a4a3153","branch":"HEAD"},"phetcommon":{"sha":"33aef589","branch":"HEAD"},"query-string-machine":{"sha":"9ae63aab","branch":"HEAD"},"scenery":{"sha":"60286436","branch":"HEAD"},"scenery-phet":{"sha":"dc31f4d9","branch":"HEAD"},"sherpa":{"sha":"0989d371","branch":"HEAD"},"sun":{"sha":"0677cbd6","branch":"HEAD"},"tambo":{"sha":"fe63321c","branch":"HEAD"},"tandem":{"sha":"f9cfcc67","branch":"HEAD"}}

</details>

**Comment by arouinfar** [comment]
@mbarlow12, if the value is 0, can you simply display 0.00?

**Comment by mbarlow** [comment]
@arouinfar wrong mbarlow :)

**Comment by mbarlow12** [comment]
Quite easy! @arouinfar do you want 0.00 for all levels of precision? e.g. the atomic screen would show 0.000 000 000 at the moment. Let me know what you'd like to see.

**Comment by arouinfar** [comment]
@mbarlow12 let's keep  0.000 000 000 for non-scientific notation on the Atomic Scale Screen.

**Comment by KatieWoe** [comment]
@arouinfar I did notice that non-scientific notation for Macro scale is 0.000 N instead.  It looks like this is on purpose though.

**Comment by arouinfar** [comment]
Correct @KatieWoe. @mbarlow12 was asking about the Atomic Scale screen, so I edited my previous comment to clarify I was talking about the Atomic Scale screen.

Macro Scale should stay 0.000 N in non-scientific notation, as that would be the consistent number of sig figs.

**Comment by mbarlow12** [comment]
@arouinfar is it alright if we display 0.00 on _both_ screens when reading in scientific notation? This results in 0.000 -> 0.00 in macro screen when checking/unchecking the checkbox. Just want to be sure on this since the discussion has been about the atomic screen mostly.

**Comment by arouinfar** [comment]
That's correct @mbarlow12. The idea is that zero would be displayed with a consistent number of decimal places depending on the screen/notation. Basically, the number of decimal places would match the non-zero values. To summarize:

**Macro Scale Screen**
* Standard: 0.000
* Scientific: 0.00

**Atomic Scale Screen**
* Standard: 0.000 000 000
* Scientific: 0.00

**Comment by mbarlow12** [comment]
Understood—thanks!

**Comment by mbarlow12** [comment]
See links for fixes:
https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.5/phet/coulombs-law_en_phet.html
https://github.com/phetsims/QA/issues/221

**Comment by arouinfar** [comment]
Looks good @mbarlow12!

**Comment by KatieWoe** [comment]
Looks good on 1.0.0-rc.5
