### ISSUE TITLE
Overlap of q1 and q2

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/coulombs-law#78]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Firefox
**Problem description:**
For https://github.com/phetsims/QA/issues/214.
When stringTest is longer than normal (double, long, rtl, etc.) the q1 and q2 labels overlap.
Steps to reproduce:
1. Set stringTest=double
2. Go to the Atomic Scale screen
3. Drag the atoms close to each other and observe the labels

**Screenshots:**
![overlap](https://user-images.githubusercontent.com/41024075/48022301-1003dd00-e0f8-11e8-9058-8b15075cec44.PNG)
![overlaptwo](https://user-images.githubusercontent.com/41024075/48022308-142ffa80-e0f8-11e8-919e-9620e5135294.PNG)

Troubleshooting information (do not edit):

<details>

Name: ‫تست (زبان)‬
URL: https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.4/phet/coulombs-law_en_phet.html?stringTest=rtl
Version: 1.0.0-rc.4 2018-10-30 20:35:59 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
Language: en-US
Window: 1536x760
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"7751fab5","branch":"HEAD"},"brand":{"sha":"1fd6682e","branch":"HEAD"},"chipper":{"sha":"fc5919bb","branch":"HEAD"},"coulombs-law":{"sha":"46b9481c","branch":"HEAD"},"dot":{"sha":"dcccfddd","branch":"HEAD"},"inverse-square-law-common":{"sha":"aec59098","branch":"HEAD"},"joist":{"sha":"b12072c7","branch":"HEAD"},"kite":{"sha":"380cef53","branch":"HEAD"},"phet-core":{"sha":"4404c06b","branch":"HEAD"},"phet-io":{"sha":"a7436d70","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"534dc595","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"3372700d","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"09507f4d","branch":"HEAD"},"phet-io-wrappers":{"sha":"0a4a3153","branch":"HEAD"},"phetcommon":{"sha":"33aef589","branch":"HEAD"},"query-string-machine":{"sha":"9ae63aab","branch":"HEAD"},"scenery":{"sha":"60286436","branch":"HEAD"},"scenery-phet":{"sha":"dc31f4d9","branch":"HEAD"},"sherpa":{"sha":"0989d371","branch":"HEAD"},"sun":{"sha":"0677cbd6","branch":"HEAD"},"tambo":{"sha":"fe63321c","branch":"HEAD"},"tandem":{"sha":"f9cfcc67","branch":"HEAD"}}

</details>

**Comment by arouinfar** [comment]
Thanks @KatieWoe. It's unlikely that the q's are going to be internationalized to anything other than 
q's (or a single character, for that matter), and the strings would only overlap for a small number of configurations. I don't think there's anything we need to do here.
