### ISSUE TITLE
branch: a11yTest

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/coulombs-law#79]
Transient branch to explore a fix for https://github.com/phetsims/scenery/issues/891

**Comment by zepumph** [comment]
@jessegreenberg can this branch be deleted?

**Comment by jessegreenberg** [comment]
Thanks, yes I am sure it can be. I don't see any changes on the branch anyway other than updates to dependencies.json, I am not clear now what was tested.

**Comment by jessegreenberg** [comment]
Branch a11yTest is no more.

**Comment by zepumph** [comment]
Should be re-deleted as part of phetsims/special-ops#198

**Comment by zepumph** [comment]
Deleted
