### ISSUE TITLE
Dynamic thumb color

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/coulombs-law#8]
In the design document, a thumb color that changes with slider value was requested.  @arouinfar should the thumb color have the same color as the mass or just swap from dark red to dark blue?

**Comment by arouinfar** [comment]
Great question @jessegreenberg. I don't think the slider thumb needs to match the exact color of the charge, as it may potentially be a bit too distracting. Three slider thumb colors (blue for negative, gray for zero, red for positive) should be sufficient. The color change may still catch a student's attention, but it would happen at a pedagogically useful time (when the force changes direction or becomes zero).

**Comment by jessegreenberg** [comment]
Sounds good @arouinfar, thanks! Assigning to @mbarlow12, we will work on this.

**Comment by jessegreenberg** [comment]
The HSlider thumb is private and there is no way to access it through NumberControl.  However, HSliders can use custom thumbs through their options.  @mbarlow12 I think the best way to handle this is to 
- Create a custom slider, presumably using HSliderThumb
- Pass it as an option to the NumberControl in ObjectControl
- Link the object value property to the custom thumb fill

**Comment by mbarlow12** [comment]
Before we move too far with this, I wanted to raise a concern given the relative difficulty to implement the changing thumb color. The feature seems visually redundant. With the sign of each charge indicated on the charges themselves, it doesn't appear like the thumb adds any additional info. @arouinfar If you'd like us to keep moving on this, that's a-ok—I just wanted to bring it up.

**Comment by arouinfar** [comment]
Thanks for asking @mbarlow12. From @jessegreenberg's https://github.com/phetsims/coulombs-law/issues/8#issuecomment-302758544 it sounds like there would need to be significant changes to HSlider or we would need to create a new slider altogether. Is that correct? If so, I don't think a color-changing thumb is worth it.

**Comment by jessegreenberg** [comment]
No, not significant, HSlider and NumberControl support custom thumbs.  A few sims already use the method in https://github.com/phetsims/coulombs-law/issues/8#issuecomment-302758544 to use a custom thumb.  But @arouinfar what do you think about 
> The feature seems visually redundant. With the sign of each charge indicated on the charges themselves, it doesn't appear like the thumb adds any additional info.

**Comment by jessegreenberg** [comment]
In https://github.com/phetsims/coulombs-law/issues/8#issuecomment-302758544 a clumsy typo made it sound much worse than it is, sorry! Should be

> Create a custom ~~slider~~ **thumb**, presumably using HSliderThumb

**Comment by jessegreenberg** [comment]
@arouinfar, do you have any thoughts on this issue given https://github.com/phetsims/coulombs-law/issues/8#issuecomment-304130920?

**Comment by arouinfar** [comment]
Looks like I lost track of this issue. Thanks the bump @jessegreenberg.

> With the sign of each charge indicated on the charges themselves, it doesn't appear like the thumb adds any additional info.

@mbarlow12 is correct here. While the thumb color isn't technically adding any new information, I think it will serve as a visual cue to reinforce the sign of the charge to users. I think the thumb color would actually be a bit more salient than the negative sign in the readout, so I would still like to proceed with the dynamic thumb color.

**Comment by jessegreenberg** [comment]
Thanks @arouinfar.  @mbarlow12 looking for an example, I couldn't find another sim that does this. But I think the approach in https://github.com/phetsims/coulombs-law/issues/8#issuecomment-302758544 should still work.

**Comment by arouinfar** [comment]
@jessegreenberg Bending Light and Color Vision have dynamic thumbs, but perhaps the difference here is that we're not mapping the thumb color as precisely?

**Comment by jessegreenberg** [comment]
Thanks @arouinfar I forgot about those.  Unfortunately, bending-light and color-vision use a type called WavelengthSlider, which has the dynamic thumb color built into its implementation and is very different from HSlider.

**Comment by arouinfar** [comment]
Thanks for the clarification @jessegreenberg. I didn't realize those weren't instances of HSlider.

**Comment by mbarlow12** [comment]
Barring a final code and color/design review, this issue can be closed. @jessegreenberg would you mind checking my work when you have a chance?

**Comment by jessegreenberg** [comment]
This is working great @mbarlow12, thanks. Code in the above commits look good.

ChargeControlSliderThumb has this code:
```js
    // remove default & duplicate button listeners
    for (var i = this.inputListeners.length - 1; i >= 0; i--) {
      if ( this.inputListeners[ i ] instanceof ButtonListener ) {
        this.removeInputListener( this.inputListeners[ i ] );
      }
    }

    // create & attach custom button listener to handle hover and up events
    this.addInputListener( new ButtonListener( {
      over: function( event ) {
        self.fill = self.baseThumbFill.colorUtilsBrighter( 0.25 );
      },
      up: function ( event ) {
        self.fill = self.baseThumbFill;
      }
    } ) );
```

I forgot about this aspect of the thumb, good catch @mbarlow12.  I am wondering if this will have the potential to strip off too many listeners in the future, and we need to re implement the input listener.

**Comment by jessegreenberg** [comment]
@mbarlow12 scenery has a really neat feature that allows strokes to be fills to be axon Properties, I am wondering if we can leverage that so that we don't have to remove input listeners from the supertype.

**Comment by jessegreenberg** [comment]
In the above commit I removed the ButtonListeners and replaced with DerivedProperties, passing those directly into the thumb fill options.  @mbarlow12 what do you think of this approach?

**Comment by mbarlow12** [comment]
Looks good to me. Closing.
