### ISSUE TITLE
Pointer Areas on ruler a bit large

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/coulombs-law#80]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/214.  Not restricted by device/browser.
The pointer area bounds on the rulers on both screens are a bit large and may lead to them being dragged when they were not clicked on.  Is this intended?
**Steps to reproduce:**
1. Set showPointerAreas
2. Enter either screen
3. Drag off the ruler, but still within the pointer area

**Screenshots:**
![drag](https://user-images.githubusercontent.com/41024075/48093972-149ac500-e1ce-11e8-9237-098df92f5832.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Coulomb's Law‬
URL: https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.4/phet/coulombs-law_en_phet.html
Version: 1.0.0-rc.4 2018-10-30 20:35:59 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"7751fab5","branch":"HEAD"},"brand":{"sha":"1fd6682e","branch":"HEAD"},"chipper":{"sha":"fc5919bb","branch":"HEAD"},"coulombs-law":{"sha":"46b9481c","branch":"HEAD"},"dot":{"sha":"dcccfddd","branch":"HEAD"},"inverse-square-law-common":{"sha":"aec59098","branch":"HEAD"},"joist":{"sha":"b12072c7","branch":"HEAD"},"kite":{"sha":"380cef53","branch":"HEAD"},"phet-core":{"sha":"4404c06b","branch":"HEAD"},"phet-io":{"sha":"a7436d70","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"534dc595","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"3372700d","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"09507f4d","branch":"HEAD"},"phet-io-wrappers":{"sha":"0a4a3153","branch":"HEAD"},"phetcommon":{"sha":"33aef589","branch":"HEAD"},"query-string-machine":{"sha":"9ae63aab","branch":"HEAD"},"scenery":{"sha":"60286436","branch":"HEAD"},"scenery-phet":{"sha":"dc31f4d9","branch":"HEAD"},"sherpa":{"sha":"0989d371","branch":"HEAD"},"sun":{"sha":"0677cbd6","branch":"HEAD"},"tambo":{"sha":"fe63321c","branch":"HEAD"},"tandem":{"sha":"f9cfcc67","branch":"HEAD"}}

</details>

**Comment by arouinfar** [comment]
Good find @KatieWoe. I see no reason for the touch or click areas to extend beyond the physical boundary of the ruler @mbarlow12.

**Comment by mbarlow12** [comment]
Thanks for _pointing_ that out!!!

(sorry, couldn't resist)

Pointer and touch area bounds reduced to the edge of the ruler in the above commits on the RC branches.

**Comment by mbarlow12** [comment]
See links for fixes:
https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.5/phet/coulombs-law_en_phet.html
https://github.com/phetsims/QA/issues/221

**Comment by KatieWoe** [comment]
Looks good.

**Comment by KatieWoe** [comment]
Looking at 1.0.0-rc.5 a more significant problem seems to emerge.  When you drag the ruler the pointer area seems to stay there.  When you move your mouse to the stationary pointer area it changes to a hand even though the ruler is gone.  Sorry @mbarlow12 for not catching earlier.
![points](https://user-images.githubusercontent.com/41024075/49108842-63c09c80-f246-11e8-8a31-6f323eba6bf1.gif)
Edit: dragging the stationary pointer area causes the ruler to move.

**Comment by arouinfar** [comment]
https://github.com/phetsims/coulombs-law/issues/80#issuecomment-442201335 seems like a separate issue, which has been reported in  https://github.com/phetsims/coulombs-law/issues/91. I'll move @KatieWoe's comment to that issue, and close this one.
