### ISSUE TITLE
Basic Actions Items in Keyboard Nav dialog could be longer

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/coulombs-law#81]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/214.  Not specific to platform/browser.
The translated strings in the Basic Action section (bottom right of dialog) have a smaller maximum width than the other sections so they get smaller faster.
**Steps to reproduce:**
1. Set stringTest=long
2. Open the Keyboard nav dialog.
3. Compare the bottom right section to the other three sections.

**Screenshots:**
![tooshort](https://user-images.githubusercontent.com/41024075/48148011-fee0da80-e275-11e8-90be-85e93de89ac5.PNG)

Troubleshooting information (do not edit):

<details>

Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.4/phet/coulombs-law_en_phet.html?stringTest=long
Version: 1.0.0-rc.4 2018-10-30 20:35:59 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"7751fab5","branch":"HEAD"},"brand":{"sha":"1fd6682e","branch":"HEAD"},"chipper":{"sha":"fc5919bb","branch":"HEAD"},"coulombs-law":{"sha":"46b9481c","branch":"HEAD"},"dot":{"sha":"dcccfddd","branch":"HEAD"},"inverse-square-law-common":{"sha":"aec59098","branch":"HEAD"},"joist":{"sha":"b12072c7","branch":"HEAD"},"kite":{"sha":"380cef53","branch":"HEAD"},"phet-core":{"sha":"4404c06b","branch":"HEAD"},"phet-io":{"sha":"a7436d70","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"534dc595","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"3372700d","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"09507f4d","branch":"HEAD"},"phet-io-wrappers":{"sha":"0a4a3153","branch":"HEAD"},"phetcommon":{"sha":"33aef589","branch":"HEAD"},"query-string-machine":{"sha":"9ae63aab","branch":"HEAD"},"scenery":{"sha":"60286436","branch":"HEAD"},"scenery-phet":{"sha":"dc31f4d9","branch":"HEAD"},"sherpa":{"sha":"0989d371","branch":"HEAD"},"sun":{"sha":"0677cbd6","branch":"HEAD"},"tambo":{"sha":"fe63321c","branch":"HEAD"},"tandem":{"sha":"f9cfcc67","branch":"HEAD"}}

</details>

**Comment by arouinfar** [comment]
Thanks @KatieWoe.

It looks like the left column, Charge Amount, and Basic Actions all have different max widths. 
![image](https://user-images.githubusercontent.com/8419308/48149116-947d6980-e278-11e8-8ff0-ab5cfe8226c7.png)

@mbarlow12 can you apply the same max width to all of the strings in the columns? If there's enough room, can you match the max width used for Charge Amount? If not, the max width used for the left two sections would also work.

**Comment by KatieWoe** [comment]
In the same vein, it looks like the scientific notation and force values strings could be longer as well. @arouinfar 
![tooshorttwo](https://user-images.githubusercontent.com/41024075/48153163-d57a7b80-e282-11e8-8c7f-6a0eee28afb1.PNG)

**Comment by arouinfar** [comment]
Good find @KatieWoe. The maxwidth of Scientific Notation and Force Values could be longer, as it looks like there's some dead space to the right of the strings.

**Comment by mbarlow12** [comment]
See links for fixes:
https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.5/phet/coulombs-law_en_phet.html
https://github.com/phetsims/QA/issues/221

**Comment by KatieWoe** [comment]
I think this looks good.  @arouinfar ?

**Comment by arouinfar** [comment]
Looks good, thanks @mbarlow12!
