### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by arouinfar** [phetsims/coulombs-law#82]
For https://github.com/phetsims/QA/issues/221

Just realized we don't have any screenshots for this sim! Self-assigning to create some screenshots.

Looks like this slipped through the cracks during code review, but this sim doesn't have an assets directory. @mbarlow12 can you create the assets directory?

**Comment by arouinfar** [comment]
@KatieWoe let's go with these screenshots. The assets directory is currently missing, so once @mbarlow12 adds it, you can commit the screenshots.

Main:
![image](https://user-images.githubusercontent.com/8419308/48652157-4de7e780-e9bb-11e8-9ebe-af20cd444910.png)

Alternates:
![image](https://user-images.githubusercontent.com/8419308/48652190-7374f100-e9bb-11e8-8fa4-6d2717c08e46.png)
![image](https://user-images.githubusercontent.com/8419308/48652240-b931b980-e9bb-11e8-958c-490e288035ca.png)

**Comment by KatieWoe** [comment]
Here are the screenshots.  Will put in github when assets is made.  Do they need to go in anything besides the main branch?
![coulombs-law-screenshot](https://user-images.githubusercontent.com/41024075/48791470-0f01ac80-ecaf-11e8-8131-1fc10589868f.png)
![coulombs-law-screenshot-alt1](https://user-images.githubusercontent.com/41024075/48791471-0f01ac80-ecaf-11e8-8657-55d6c825a3c1.png)
![coulombs-law-screenshot-alt2](https://user-images.githubusercontent.com/41024075/48791472-0f01ac80-ecaf-11e8-9580-56e700ec66c8.png)

**Comment by arouinfar** [comment]
Thanks @KatieWoe! I would put them in master and 1.0 once the assets directory has been created.

**Comment by KatieWoe** [comment]
Above commits should do it.  Please review and close if acceptable.

**Comment by arouinfar** [comment]
Looks good @KatieWoe!
