### ISSUE TITLE
Update color of dashed lines 

### ISSUE THREAD

**Issue by arouinfar** [phetsims/coulombs-law#87]
For https://github.com/phetsims/QA/issues/221

In GFL(B), the color of the dashed lines was meant to match up with the masses. In CL, charges can be red or blue, which can lead to this somewhat odd-looking situation.
![image](https://user-images.githubusercontent.com/8419308/49120422-c7a88c80-f269-11e8-9c48-381e60c815df.png)

We could either

1. Make both lines gray. `rgb(180, 180, 180)` would work nicely.
<img src="https://user-images.githubusercontent.com/8419308/49121025-3c7cc600-f26c-11e8-869a-4cba92ad3ae3.png" width=150>

2. Make the line color adaptive like the Charge slider thumbs: blue when negative, red when positive, gray when zero.

Option (2) would look a bit nicer, but option (1) seems quicker/easier. If option (2) is a quick(ish) and non-invasive change (the next rc could still be a spot check), then I'd like to pursue it @mbarlow12. Otherwise, let's go with option (1).

**Comment by mbarlow12** [comment]
@arouinfar I was able to have the color update along with the charge value. The colors themselves are a little muted compared to the slider thumb, but that can easily be changed if desired.

**Comment by arouinfar** [comment]
That's great @mbarlow12. I pulled all, but I'm not seeing any color changes. Did you commit the changes to master?

**Comment by mbarlow12** [comment]
No I didn't. They're made in 1.0 branch currently. I'll be sure to pull them ASAP.

**Comment by mbarlow12** [comment]
@arouinfar I just merged the branches into master.

**Comment by arouinfar** [comment]
Looks awesome @mbarlow12! Thanks.

**Comment by KatieWoe** [comment]
1.0.0-rc.6 this looks good.
