### ISSUE TITLE
Dilate touch areas on charge NumberControls

### ISSUE THREAD

**Issue by arouinfar** [phetsims/coulombs-law#89]
For https://github.com/phetsims/QA/issues/221

@kathy-phet commented that the charge controls were a bit tricky to use on mobile, and recommended dilating the touch areas a bit.

There's plenty of room, so I think something like this would be helpful @mbarlow12.
<img width="559" alt="screen shot 2018-11-28 at 8 38 30 am" src="https://user-images.githubusercontent.com/8419308/49162874-177a6880-f2e9-11e8-8bfd-daa62c66157a.png">

**Comment by kellywurtz** [comment]
On rc.6, looks like the slider touch area size increased, but not the arrows. Looking on Windows 10 Chrome. 

![image](https://user-images.githubusercontent.com/42352972/49600222-f1377700-f93f-11e8-81b5-2aaee66df07b.png)

**Comment by arouinfar** [comment]
Good catch @kellywurtz. @kathy-phet's original concern was more with the tweakers, so it'd be good to fix @mbarlow12.

**Comment by arouinfar** [comment]
Tagging https://github.com/phetsims/QA/issues/235 so this issue shows up in the list.

@mbarlow12 I don't see any recent commits here, so not sure if https://github.com/phetsims/coulombs-law/issues/89#issuecomment-444953246 was addressed or not.

**Comment by kathy-phet** [comment]
phettest looks smaller than the above screenshot, so something looks like it was reverted. Do please increase both tweekers and thumb.
![image](https://user-images.githubusercontent.com/5096804/50246287-26a58100-0392-11e9-9c23-042114e019a1.png)

**Comment by kathy-phet** [comment]
The above was seen on phettest. Amy thought that perhaps the change Kelly saw was not done on master? @mbarlow12 - please make sure master has any of the fixes too.

**Comment by KatieWoe** [comment]
This looks good 1.0.0-rc.8
