### ISSUE TITLE
Charges jump when keyboard nav is used

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/coulombs-law#90]
**Device**
hp Laptop
**OS**
Win 7
**Browser**
IE
**Problem Description**
For https://github.com/phetsims/QA/issues/221.  Issue doesn't appear on all platforms.  When keyboard nav is used to highlight one of the charge figures, that figure may jump to the side slightly.
**Steps to Reproduce**
1. Open the sim with internet explorer
2. Go to either screen
3. Use keyboard nav to move one of the figures back and forth
4. Change focus to the second figure (shift may or may not occur here) and move it back and forth.
5. Change focus back to original figure

**Screenshot**
https://drive.google.com/file/d/1P2hIV0E6J9TjowqtjYmlpzoVAkMyRKdk/view?usp=sharing

**Comment by jessegreenberg** [comment]
I observed this often while looking into #86 (only in Edge)

**Comment by jessegreenberg** [comment]
This is caused by the step size, which is 0.1 in this sim.
```js
          this.setAccessibleAttribute( 'step', Math.pow( 10, -options.accessibleDecimalPlaces ) );
```

If I change accessibleDecimalPlaces in this sim to 3, the problem goes away. From https://github.com/phetsims/sun/issues/413, I think we need to make this a required parameter or change how this is set.

**Comment by jessegreenberg** [comment]
If I use "any" as the value for the step attribute, this problem goes away, see phetsims/sun#413

**Comment by jessegreenberg** [comment]
@KatieWoe this should be fixed with https://github.com/phetsims/sun/commit/31b65ddaeb9cfe49c99968c79952b6ce42ef1f97, can you please confirm?

**Comment by KatieWoe** [comment]
Seems to be fixed on master version of Coulomb's Law using Win 10 Internet explorer.

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, sounds good. Sun SHA https://github.com/phetsims/sun/commit/31b65ddaeb9cfe49c99968c79952b6ce42ef1f97 is the one we will need for the RC. @mbarlow12 if you run into any trouble pulling in the change please let me know.

**Comment by mbarlow12** [comment]
@jessegreenberg thanks—will do.

**Comment by KatieWoe** [comment]
1.0.0-rc.6 looks good on Win 10 IE
