### ISSUE TITLE
Ruler pointer area gets left behind when ruler is moved

### ISSUE THREAD

**Issue by rea-laura** [phetsims/coulombs-law#91]
<b>Test Device</b>

Jordan

<b>Operating System</b>

iOS Mojave 10.14.1

<b>Browser</b>

Chrome 70.0.3538.110

<b>Problem Description</b>

In https://github.com/phetsims/QA/issues/221:
When ruler is moved, the pointer area remains in the ruler's original spot. User can then interact with the ruler by selecting either the ruler item or the space where it used to be.

Also appears in Firefox and on Windows operating systems.

<b>Steps to Reproduce</b>

1) open sim with pointer area query parameter: https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.5/phet/coulombs-law_en_phet.html?showPointerAreas
2) move the ruler
3) note that the pointer area does not move with the ruler. User can now select both the ruler object or the ruler pointer area to interact with the ruler.
4) this happens in the sim with the query parameter and without the query parameter. The query parameter merely helps visualize the problem.

<b>Visuals</b>

Recordings of the problem:
https://photos.app.goo.gl/hjm9WBYAkVFbS6eD7
https://photos.app.goo.gl/upgLMTHB6fdigNMi6

**Comment by arouinfar** [comment]
@KatieWoe has also noticed this issue in https://github.com/phetsims/coulombs-law/issues/80#issuecomment-442201335. Here's her description:

> Looking at 1.0.0-rc.5 a more significant problem seems to emerge.  When you drag the ruler the pointer area seems to stay there.  When you move your mouse to the stationary pointer area it changes to a hand even though the ruler is gone.  Sorry @mbarlow12 for not catching earlier.
![points](https://user-images.githubusercontent.com/41024075/49108842-63c09c80-f246-11e8-8a31-6f323eba6bf1.gif)
Edit: dragging the stationary pointer area causes the ruler to move.

**Comment by KatieWoe** [comment]
1.00-rc.6 this is fixed
