### ISSUE TITLE
Reentry detected in Edge

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/coulombs-law#92]
For some reason, I am seeing reentry errors in master, but so far only in edge. Happens when updating the range of the objects.

My guess right now is that the flow is like
- Position changes
  - Force changes
    - enabled range changes
      - forces position to change?
     
Assigning to @mbarlow12 because he is responsible dev, but also myself since I have easy access to Edge.

**Comment by jessegreenberg** [comment]
I see in the call stack that we are handling both input AND keydown in edge. I would have expected               event.preventDefault(); to prevent this.

**Comment by jessegreenberg** [comment]
This is also definitely the cause of #90

**Comment by jessegreenberg** [comment]
It appears that preventDefault isn't working because input event isn't cancelable (like the change event). So we need to do something else. This isn't a problem because Chrome doesn't trigger the input event on sliders.

**Comment by jessegreenberg** [comment]
@mbarlow12 I verified that this doesn't impact the coulombs-law RC because handleInput was added to AccessibleSlider after SHAS for 1.0 were taken.

**Comment by arouinfar** [comment]
While not strictly for https://github.com/phetsims/QA/issues/221, I'm tagging it because this'll need to be addressed before publication.

**Comment by jessegreenberg** [comment]
Setting the 'min' attribute is causing the `input` event to trigger.
```self.setAccessibleAttribute( 'min', enabledRange.min );```,

And so is blur (sometimes).

**Comment by jessegreenberg** [comment]
One potential fix is to block input events when changing the min and max attributes. After fuzz testing and manual testing I haven't been able to reproduce the bug. But this didn't fix #90 and I still think they may be related so Ill investigate that issue before commiting this.

**Comment by jessegreenberg** [comment]
If I use "any" as the value for the step attribute, this problem goes away, see https://github.com/phetsims/sun/issues/413

**Comment by jessegreenberg** [comment]
Input event is still triggered sometimes when range of slider updates.

The flow of reentry is
- position changes
  - force changes
    - enabled range changes
      - triggers an input event
        - input listener triggers position change

**Comment by jessegreenberg** [comment]
The above commit blocks input events after capturing a keydown event, which is OK since `keydown` handles all keyboard logic and `input` is purely there for assistive devices without keyboards. This has been fixed in master, and doesn't need to be included in the release since RC shas of sun with AccessibleSlider don't include `handleInput`. Closing.
