### ISSUE TITLE
Sometimes ruler can't be moved

### ISSUE THREAD

**Issue by ghost** [phetsims/coulombs-law#95]
For https://github.com/phetsims/QA/issues/235. The only confirmed sighting of this bug is on Win10 + Edge. It's basically the title. I have no idea how to reproduce. I will edit this issue and add details when/if I have more info.

**Comment by mbarlow12** [comment]
@lmulhall-phet Do you have any updates or more details?

**Comment by ghost** [comment]
Unfortunately, no. I spent a good long while trying to find a way to reproduce and sadly I didn’t find a way. Katie and I are beginning to think it was a fluke.

Katie did witness the bug. I’m not crazy.

Given that it’s so hard to reproduce, we might be able to safely ignore it, but I defer to you and @KatieWoe on that.

**Comment by KatieWoe** [comment]
I think it might be safe, but I'm a bit wary. @ariel-phet what do you think?

**Comment by ariel-phet** [comment]
@KatieWoe @mbarlow12 given the difficulty to reproduce (and the platform), I am totally fine closing this issue. MS is planning on getting rid of the current incarnation of Edge in favor of a browser based on Chromium, so we can take Edge bugs with a grain of salt.

Closing
