### ISSUE TITLE
Crash on iOS 10

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/coulombs-law#96]
For https://github.com/phetsims/QA/issues/235
Mentioned in QA issue.  On iOS 10 the sim froze and crashed fairly quickly. This also seemed to happen in graphing quadratics, but it was determined to be an issue with the device, which may be the case here.  I reset device and it seemed better, but crash still occurred after 10 minutes.  This is GQ issue in question: https://github.com/phetsims/graphing-quadratics/issues/116.

**Comment by KatieWoe** [comment]
showPointerAreas caused crash very quickly.  This typically lowers performance, but may cause concern.

**Comment by pixelzoom** [comment]
Slack:

Chris Malley [1:56 PM]
Hmmm.. As I recall, GQ crashed with “A problem occurred with this webpage so it was reloaded”, and then reloaded.   It sounds like CL is crashing and freezing, which is different.


Kathryn Woessner [1:57 PM]
It did both.  At first it froze.  I refreshed and then it crashed with the error message and refreshed itself.  Its crashed with the error message a few time since.
It hasn't frozen since.

**Comment by KatieWoe** [comment]
Attempted to recreate while tethered to console.  For some reason, even when showPointerAreas was on, the sim did not crash.  Performance was low.  No error showed in the console.

**Comment by KatieWoe** [comment]
Clearing cache, running in private mode, and clearing all website data did not solve the problem.

**Comment by KatieWoe** [comment]
Playing with graphing quadratics with showPointerAreas for a few minutes did not produce the same behavior.  I think now this is an issue with the sim and not the device.

**Comment by KatieWoe** [comment]
Crash occurs when using on Legends of Learning very quickly.  To the point that I can't test legendsOfLearning.

**Comment by KatieWoe** [comment]
Only seemed to effect the iOS 10.

**Comment by mbarlow12** [comment]
@KatieWoe so it's only on iOS 10 when using LOL? or iOS 10 in general?

**Comment by KatieWoe** [comment]
iOS 10 in general is crashing with this sim, and doing so particularly fast when on LoL.

**Comment by ariel-phet** [comment]
@KatieWoe can you do two things for me:

1. Can you try running this sim from master on iOS10 and see if it crashes (just as another data point)
2. Can you try running Gravity Force Lab from the website and see if it crashes https://phet.colorado.edu/en/simulation/gravity-force-lab

**Comment by KatieWoe** [comment]
1. I put showPointerAreas on CL master and after several minutes it does not seem to be crashing (though there are two pointer areas around the ruler).
2. Have not gotten GFL to crash after several minutes.
@ariel-phet

**Comment by mbarlow12** [comment]
@KatieWoe I don't have access to an iOS 10 device. Is there any other info you can provide? In https://github.com/phetsims/graphing-quadratics/issues/116#issuecomment-445967914, you implied it might have to do with the device. Has the crash been observed on a different iOS 10 device?

**Comment by KatieWoe** [comment]
We only have one iOS 10 device, so it can't really be checked on another.  However, since I went back and did similar tests on graphing-quadratics, master version of CL, and published GFL and did not see nearly the same behavior I think my initial assessment that it was the device was premature.

**Comment by mbarlow12** [comment]
@KatieWoe what's the Safari version? And are there any logs, console, or error messages?

**Comment by KatieWoe** [comment]
Safari version is the same as the OS since mobile safari is tied to iOS, so 10.3.3.  I tethered the iOS 10 device to a Mac and looked at the console yesterday but there were no errors/messages and for some reason it seemed to prevent the sim from crashing, even with showPointerAreas on.  Performance was still poor, but the sim would not crash.  Disconnecting it brought the problem back with the same severity as before.

**Comment by mbarlow12** [comment]
Would you be willing to perform the same tests on the RC 5 and 4 releases? The [test harness for 4](https://docs.google.com/spreadsheets/d/17BEdTv1KM1Tq6kyi3fxo15znqRH6iw8pyc4axE47eeM/edit#gid=1380557997) indicates that iOS 10 passed at that point, while the RC5 spot check doesn't look like it touched that.

**Comment by mbarlow12** [comment]
Perhaps we can isolate the changes or dependency updates that have led to this.

**Comment by phet-steele** [comment]
> Safari version is the same as the OS since mobile safari is tied to iOS, so 10.3.3.

The version number of Safari in that iOS is 602.1 (it's in the user agent of the troubleshooting info and what you should be putting in the test matrices). This is important since safari 602.1 is used in ALL versions of iOS 10 (so 10.0, 10.0.1. 10.0.2, etc...), not just 10.3.3.

**Comment by KatieWoe** [comment]
@phet-steele that's good to know.  Thanks

**Comment by KatieWoe** [comment]
So this is super weird.  I just pulled up rc.6 to get a baseline on it, and it seems to be fine right now.  No crashing, even with LoL, where it crashed in a few seconds before.  Nothing I tried with the device was fixing it the other day and now it seems to be better.  I'm really baffled, but it's back to maybe not being a problem with the sim.

**Comment by arouinfar** [comment]
This was tested again in the last rounds of rc testing, and it doesn't look like there were any issues. I'm going to go ahead and close this, but if the problem resurfaces, we can always reopen.
