### ISSUE TITLE
Forces are not equal and opposite

### ISSUE THREAD

**Issue by rea-laura** [phetsims/coulombs-law#97]
<b>Test Device</b>

Leibniz

<b>Operating System</b>

iOS 12.1

<b>Browser</b>

Safari 12.1

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/242:
When one mass is moved, the other's force will not update until it is moved as well. 

Occurs on all platforms tested so far (iOS 12, MacOS 10.14 Safari and Firefox, Windows 10 chrome)

<b>Steps to Reproduce</b>

1) open sim
2) note that at the beginning, forces are equal and opposite.
3) move one object, or change its charge. The other mass will not change force value. This affects the length of the force arrows, and the position of the figure pulling/pushing.

<b>Visuals</b>

![image](https://user-images.githubusercontent.com/44005544/50304550-7f861f80-044d-11e9-8754-0334e0dbf602.png)

**Comment by arouinfar** [comment]
Yikes, nice find @rea-laura.

Strangely, this bug doesn't appear to be in master, or the other ISLC siblings.

**Comment by mbarlow12** [comment]
I had some lines commented out while dealing with the issue for text going off screen. Sorry for the confusion.

**Comment by arouinfar** [comment]
Since QA is early on in the spot check, would it be better to publish a new rc and test that instead @mbarlow12 @ariel-phet?

**Comment by mbarlow12** [comment]
I'm investigating just re-releasing the same RC. If that's not ok, I'll bump to RC.8.

**Comment by kathy-phet** [comment]
Last time I asked JO about this, he said in general bumping the RC is easiest.

**Comment by mbarlow12** [comment]
Ok—will do.

**Comment by mbarlow12** [comment]
New RC:
https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.8/phet/coulombs-law_en_phet.html

**Comment by kathy-phet** [comment]
thx

**Comment by KatieWoe** [comment]
This seems fixed in 1.0.0-rc.8
